#############################################################################
# Makefile for building: client_2.12
# Generated by qmake (1.05a) (Qt 3.1.2) on: Thu Jun 17 18:39:36 2010
# Project:  client.pro
# Template: app
# Command: $(QMAKE) -o Makefile client.pro
#############################################################################

!if !$d(BCB)
BCB = $(MAKEDIR)\..
!endif

####### Compiler, tools and options

CC	=	bcc32
CXX	=	bcc32
LEX     = flex
YACC    = byacc
CFLAGS	=	-tWR -w -w-hid -tWM -O2 -x- -RT-  -DUNICODE -DQT_DLL -DQT_THREAD_SUPPORT -DQT_NO_DEBUG
CXXFLAGS=	-tWR -w -w-hid -tWM -O2 -x- -RT-  -DUNICODE -DQT_DLL -DQT_THREAD_SUPPORT -DQT_NO_DEBUG
LEXFLAGS=
YACCFLAGS=-d
INCPATH	=	 -I"$(QTDIR)\include" -I"Z:\affymetrix\client\mainline" -I"$(QTDIR)\mkspecs\win32-borland"
LINK	=	ilink32
LFLAGS	=	-L$(BCB)\lib;$(QTDIR)\lib -c -x -Gn /dopengl32.dll -aa -Tpe c0w32.obj
LIBS	=	import32.lib qtmt312.lib qtmain.lib cw32mti.lib
MOC	=	$(QTDIR)\bin\moc.exe
UIC	=	$(QTDIR)\bin\uic.exe
QMAKE =       qmake
IDC		=	$(QTDIR)\bin\idc.exe
IDL		=	midl
ZIP	=	zip -r -9
DEF_FILE =	
RES_FILE =	
COPY_FILE  =       copy
COPY_DIR  =       copy
DEL_FILE   =       del
DEL_DIR    =       rmdir
MOVE  =       move
CHK_DIR_EXISTS =	if not exist
MKDIR		=	mkdir

####### Files

HEADERS =	images.h \
		client.h \
		clientWindow.h \
		probe_set\probe_set.h \
		stat\stat.h \
		stat\kernelFunction.h \
		stat\twoDimDist.h \
		stat\pointPlotter.h \
		expressionplotter.h \
		socketReadFunctions.h \
		dataView.h \
		dbQuerier.h \
		plotWindow.h \
		comparisonWindow\comparisonwindow.h \
		comparisonWindow\compInputWindow.h \
		smallToggle\smallToggle.h \
		listWindow\listWindow.h \
		probeSetWidget\probeSetWidget.h \
		meanPlotWindow\meanPlotWindow.h \
		meanPlotWindow\meanExpressionPlotter.h \
		meanPlotWindow\keyWindow.h \
		exptinfo.h \
		experimentWidget\experimentWidget.h \
		experimentChooser\experimentChooser.h \
		experimentChooser\sampleMemoryWidget.h \
		experimentChooser\sampleSelectionWidget.h \
		experimentChooser\orderChooser\orderWindow.h \
		experimentChooser\orderChooser\orderWidget.h \
		bytevec\bytevec.h \
		logindialog\logindialog.h \
		passwdchange\passwdchange.h \
		blastAlignPainter\blastalignpainter.h \
		blastAlignPainter\blastAlignWidget.h \
		glPlotter\glPlotter.h \
		statPlotter\statWidget.h \
		statPlotter\statWindow.h \
		statPlotter\distChooser.h \
		statPlotter\twoDimDistLauncher.h \
		statPlotter\twoDimDistPlotter.h \
		blastAlignPainter\GenAlignWidget.h \
		annotator\annotator.h \
		annotator\newSession.h \
		annotator\sessionManager\sessionWidget.h \
		annotator\sessionManager\sessionManager.h \
		annotator\annotationWidget\annotationWidget.h \
		annotator\annotationViewer.h \
		blastAlignPainter\genAlignView.h \
		sequence\sequenceRequest.h \
		sequence\seqWidget.h \
		clusterWindow\clusterWindow.h \
		clusterWindow\clusterListItem.h \
		clusterWindow\clusterPlotter.h \
		genomicRegion\regionListItem.h \
		genomicRegion\regionWindow.h \
		genomicRegion\localRegionWidget.h \
		genomicRegion\localRegionView.h \
		jpgView\jpgView.h \
		jpgView\imageViewer.h \
		dataStructs.h \
		jpgView\thumbView.h \
		jpgView\inSituView.h \
		jpgView\ishTextEntry.h \
		jpgView\ishFloatEntry.h \
		jpgView\ishAnnotationEditor.h \
		jpgView\ishAnnotationErrorMessage.h \
		jpgView\textWidget.h \
		distanceMapper\distanceMapper.h \
		distanceMapper\pointDrawer.h \
		distanceMapper\distanceViewer.h \
		distanceMapper\tdPointDrawer.h \
		distanceMapper\traceDrawer.h \
		distanceMapper\traceViewer.h \
		distanceMapper\stressPlotter.h \
		customWidgets\fSpinBox.h \
		customWidgets\lSpinBox.h \
		distanceMapper\compareController.h \
		protocol\protocolStepWidget.h \
		protocol\protocolViewer.h \
		protocol\protocolHolder.h \
		protocol\protocolManager.h \
		protocol\protocolClipboard.h \
		experiment\experimentBrowser.h \
		experiment\experimentMaker.h \
		jpgView\imageAdder.h \
		jpgView\fieldCreator.h \
		jpgView\commentAdder.h \
		indexHistory\indexWidget.h \
		indexHistory\historyWidget.h \
		boolParser\boolParser.h \
		2dplot\2dplot.h \
		chips\chipSelection.h \
		chips\chipChooser.h \
		dialogs\exportMeanDialog.h \
		exportWindow\exportWidget.h \
		exportWindow\psDialog.h \
		exportWindow\fileDialog.h \
		sampleInfo\sampleInfoWidget.h
SOURCES =	client.cpp \
		clientWindow.cpp \
		main.cpp \
		probe_set\probe_set.cpp \
		stat\stat.cpp \
		stat\kernelFunction.cpp \
		stat\twoDimDist.cpp \
		stat\pointPlotter.cpp \
		expressionplotter.cpp \
		socketReadFunctions.cpp \
		dataView.cpp \
		dbQuerier.cpp \
		plotWindow.cpp \
		comparisonWindow\comparisonwindow.cpp \
		comparisonWindow\compInputWindow.cpp \
		smallToggle\smallToggle.cpp \
		listWindow\listWindow.cpp \
		probeSetWidget\probeSetWidget.cpp \
		meanPlotWindow\meanPlotWindow.cpp \
		meanPlotWindow\meanExpressionPlotter.cpp \
		meanPlotWindow\keyWindow.cpp \
		exptinfo.cpp \
		experimentWidget\experimentWidget.cpp \
		experimentChooser\experimentChooser.cpp \
		experimentChooser\sampleMemoryWidget.cpp \
		experimentChooser\sampleSelectionWidget.cpp \
		experimentChooser\orderChooser\orderWidget.cpp \
		experimentChooser\orderChooser\orderWindow.cpp \
		bytevec\bytevec.cpp \
		logindialog\logindialog.cpp \
		passwdchange\passwdchange.cpp \
		blastAlignPainter\blastalignpainter.cpp \
		blastAlignPainter\blastAlignWidget.cpp \
		glPlotter\glPlotter.cpp \
		statPlotter\statWidget.cpp \
		statPlotter\statWindow.cpp \
		statPlotter\distChooser.cpp \
		statPlotter\twoDimDistLauncher.cpp \
		statPlotter\twoDimDistPlotter.cpp \
		blastAlignPainter\GenAlignWidget.cpp \
		annotator\annotator.cpp \
		annotator\newSession.cpp \
		annotator\sessionManager\sessionWidget.cpp \
		annotator\sessionManager\sessionManager.cpp \
		annotator\annotationWidget\annotationWidget.cpp \
		annotator\annotationViewer.cpp \
		blastAlignPainter\genAlignView.cpp \
		sequence\sequenceRequest.cpp \
		sequence\seqWidget.cpp \
		clusterWindow\clusterWindow.cpp \
		clusterWindow\clusterListItem.cpp \
		clusterWindow\clusterPlotter.cpp \
		genomicRegion\regionListItem.cpp \
		genomicRegion\regionWindow.cpp \
		genomicRegion\localRegionWidget.cpp \
		genomicRegion\localRegionView.cpp \
		jpgView\jpgView.cpp \
		jpgView\imageViewer.cpp \
		jpgView\thumbView.cpp \
		jpgView\inSituView.cpp \
		jpgView\ishTextEntry.cpp \
		jpgView\ishFloatEntry.cpp \
		jpgView\ishAnnotationEditor.cpp \
		jpgView\ishAnnotationErrorMessage.cpp \
		jpgView\textWidget.cpp \
		distanceMapper\distanceMapper.cpp \
		distanceMapper\pointDrawer.cpp \
		distanceMapper\distanceViewer.cpp \
		distanceMapper\tdPointDrawer.cpp \
		distanceMapper\traceDrawer.cpp \
		distanceMapper\traceViewer.cpp \
		distanceMapper\stressPlotter.cpp \
		customWidgets\fSpinBox.cpp \
		customWidgets\lSpinBox.cpp \
		distanceMapper\compareController.cpp \
		dataStructs.cpp \
		protocol\protocolStepWidget.cpp \
		protocol\protocolViewer.cpp \
		protocol\protocolHolder.cpp \
		protocol\protocolManager.cpp \
		protocol\protocolClipboard.cpp \
		experiment\experimentBrowser.cpp \
		experiment\experimentMaker.cpp \
		jpgView\imageAdder.cpp \
		jpgView\fieldCreator.cpp \
		jpgView\commentAdder.cpp \
		indexHistory\indexWidget.cpp \
		indexHistory\historyWidget.cpp \
		boolParser\boolParser.cpp \
		2dplot\2dplot.cpp \
		chips\chipSelection.cpp \
		chips\chipChooser.cpp \
		dialogs\exportMeanDialog.cpp \
		exportWindow\exportWidget.cpp \
		exportWindow\psDialog.cpp \
		exportWindow\fileDialog.cpp \
		sampleInfo\sampleInfoWidget.cpp
OBJECTS =	client.obj \
		clientWindow.obj \
		main.obj \
		probe_set.obj \
		stat.obj \
		kernelFunction.obj \
		twoDimDist.obj \
		pointPlotter.obj \
		expressionplotter.obj \
		socketReadFunctions.obj \
		dataView.obj \
		dbQuerier.obj \
		plotWindow.obj \
		comparisonwindow.obj \
		compInputWindow.obj \
		smallToggle.obj \
		listWindow.obj \
		probeSetWidget.obj \
		meanPlotWindow.obj \
		meanExpressionPlotter.obj \
		keyWindow.obj \
		exptinfo.obj \
		experimentWidget.obj \
		experimentChooser.obj \
		sampleMemoryWidget.obj \
		sampleSelectionWidget.obj \
		orderWidget.obj \
		orderWindow.obj \
		bytevec.obj \
		logindialog.obj \
		passwdchange.obj \
		blastalignpainter.obj \
		blastAlignWidget.obj \
		glPlotter.obj \
		statWidget.obj \
		statWindow.obj \
		distChooser.obj \
		twoDimDistLauncher.obj \
		twoDimDistPlotter.obj \
		GenAlignWidget.obj \
		annotator.obj \
		newSession.obj \
		sessionWidget.obj \
		sessionManager.obj \
		annotationWidget.obj \
		annotationViewer.obj \
		genAlignView.obj \
		sequenceRequest.obj \
		seqWidget.obj \
		clusterWindow.obj \
		clusterListItem.obj \
		clusterPlotter.obj \
		regionListItem.obj \
		regionWindow.obj \
		localRegionWidget.obj \
		localRegionView.obj \
		jpgView.obj \
		imageViewer.obj \
		thumbView.obj \
		inSituView.obj \
		ishTextEntry.obj \
		ishFloatEntry.obj \
		ishAnnotationEditor.obj \
		ishAnnotationErrorMessage.obj \
		textWidget.obj \
		distanceMapper.obj \
		pointDrawer.obj \
		distanceViewer.obj \
		tdPointDrawer.obj \
		traceDrawer.obj \
		traceViewer.obj \
		stressPlotter.obj \
		fSpinBox.obj \
		lSpinBox.obj \
		compareController.obj \
		dataStructs.obj \
		protocolStepWidget.obj \
		protocolViewer.obj \
		protocolHolder.obj \
		protocolManager.obj \
		protocolClipboard.obj \
		experimentBrowser.obj \
		experimentMaker.obj \
		imageAdder.obj \
		fieldCreator.obj \
		commentAdder.obj \
		indexWidget.obj \
		historyWidget.obj \
		boolParser.obj \
		2dplot.obj \
		chipSelection.obj \
		chipChooser.obj \
		exportMeanDialog.obj \
		exportWidget.obj \
		psDialog.obj \
		fileDialog.obj \
		sampleInfoWidget.obj
FORMS =	
UICDECLS =	
UICIMPLS =	
SRCMOC	=	moc_client.cpp \
		moc_clientWindow.cpp \
		stat\moc_pointPlotter.cpp \
		moc_expressionplotter.cpp \
		moc_dataView.cpp \
		moc_dbQuerier.cpp \
		moc_plotWindow.cpp \
		comparisonWindow\moc_comparisonwindow.cpp \
		comparisonWindow\moc_compInputWindow.cpp \
		smallToggle\moc_smallToggle.cpp \
		listWindow\moc_listWindow.cpp \
		probeSetWidget\moc_probeSetWidget.cpp \
		meanPlotWindow\moc_meanPlotWindow.cpp \
		meanPlotWindow\moc_meanExpressionPlotter.cpp \
		meanPlotWindow\moc_keyWindow.cpp \
		experimentWidget\moc_experimentWidget.cpp \
		experimentChooser\moc_experimentChooser.cpp \
		experimentChooser\moc_sampleMemoryWidget.cpp \
		experimentChooser\moc_sampleSelectionWidget.cpp \
		experimentChooser\orderChooser\moc_orderWindow.cpp \
		experimentChooser\orderChooser\moc_orderWidget.cpp \
		logindialog\moc_logindialog.cpp \
		passwdchange\moc_passwdchange.cpp \
		blastAlignPainter\moc_blastalignpainter.cpp \
		blastAlignPainter\moc_blastAlignWidget.cpp \
		glPlotter\moc_glPlotter.cpp \
		statPlotter\moc_statWidget.cpp \
		statPlotter\moc_statWindow.cpp \
		statPlotter\moc_distChooser.cpp \
		statPlotter\moc_twoDimDistLauncher.cpp \
		statPlotter\moc_twoDimDistPlotter.cpp \
		blastAlignPainter\moc_GenAlignWidget.cpp \
		annotator\moc_annotator.cpp \
		annotator\moc_newSession.cpp \
		annotator\sessionManager\moc_sessionWidget.cpp \
		annotator\sessionManager\moc_sessionManager.cpp \
		annotator\annotationWidget\moc_annotationWidget.cpp \
		annotator\moc_annotationViewer.cpp \
		blastAlignPainter\moc_genAlignView.cpp \
		sequence\moc_seqWidget.cpp \
		clusterWindow\moc_clusterWindow.cpp \
		clusterWindow\moc_clusterPlotter.cpp \
		genomicRegion\moc_regionWindow.cpp \
		genomicRegion\moc_localRegionWidget.cpp \
		genomicRegion\moc_localRegionView.cpp \
		jpgView\moc_jpgView.cpp \
		jpgView\moc_imageViewer.cpp \
		jpgView\moc_thumbView.cpp \
		jpgView\moc_inSituView.cpp \
		jpgView\moc_ishTextEntry.cpp \
		jpgView\moc_ishFloatEntry.cpp \
		jpgView\moc_ishAnnotationEditor.cpp \
		jpgView\moc_ishAnnotationErrorMessage.cpp \
		jpgView\moc_textWidget.cpp \
		distanceMapper\moc_pointDrawer.cpp \
		distanceMapper\moc_distanceViewer.cpp \
		distanceMapper\moc_tdPointDrawer.cpp \
		distanceMapper\moc_traceDrawer.cpp \
		distanceMapper\moc_traceViewer.cpp \
		distanceMapper\moc_stressPlotter.cpp \
		customWidgets\moc_fSpinBox.cpp \
		customWidgets\moc_lSpinBox.cpp \
		distanceMapper\moc_compareController.cpp \
		protocol\moc_protocolStepWidget.cpp \
		protocol\moc_protocolViewer.cpp \
		protocol\moc_protocolHolder.cpp \
		protocol\moc_protocolManager.cpp \
		protocol\moc_protocolClipboard.cpp \
		experiment\moc_experimentBrowser.cpp \
		experiment\moc_experimentMaker.cpp \
		jpgView\moc_imageAdder.cpp \
		jpgView\moc_fieldCreator.cpp \
		jpgView\moc_commentAdder.cpp \
		indexHistory\moc_indexWidget.cpp \
		indexHistory\moc_historyWidget.cpp \
		2dplot\moc_2dplot.cpp \
		chips\moc_chipSelection.cpp \
		chips\moc_chipChooser.cpp \
		dialogs\moc_exportMeanDialog.cpp \
		exportWindow\moc_exportWidget.cpp \
		exportWindow\moc_psDialog.cpp \
		exportWindow\moc_fileDialog.cpp \
		sampleInfo\moc_sampleInfoWidget.cpp
OBJMOC	=	moc_client.obj \
		moc_clientWindow.obj \
		moc_pointPlotter.obj \
		moc_expressionplotter.obj \
		moc_dataView.obj \
		moc_dbQuerier.obj \
		moc_plotWindow.obj \
		moc_comparisonwindow.obj \
		moc_compInputWindow.obj \
		moc_smallToggle.obj \
		moc_listWindow.obj \
		moc_probeSetWidget.obj \
		moc_meanPlotWindow.obj \
		moc_meanExpressionPlotter.obj \
		moc_keyWindow.obj \
		moc_experimentWidget.obj \
		moc_experimentChooser.obj \
		moc_sampleMemoryWidget.obj \
		moc_sampleSelectionWidget.obj \
		moc_orderWindow.obj \
		moc_orderWidget.obj \
		moc_logindialog.obj \
		moc_passwdchange.obj \
		moc_blastalignpainter.obj \
		moc_blastAlignWidget.obj \
		moc_glPlotter.obj \
		moc_statWidget.obj \
		moc_statWindow.obj \
		moc_distChooser.obj \
		moc_twoDimDistLauncher.obj \
		moc_twoDimDistPlotter.obj \
		moc_GenAlignWidget.obj \
		moc_annotator.obj \
		moc_newSession.obj \
		moc_sessionWidget.obj \
		moc_sessionManager.obj \
		moc_annotationWidget.obj \
		moc_annotationViewer.obj \
		moc_genAlignView.obj \
		moc_seqWidget.obj \
		moc_clusterWindow.obj \
		moc_clusterPlotter.obj \
		moc_regionWindow.obj \
		moc_localRegionWidget.obj \
		moc_localRegionView.obj \
		moc_jpgView.obj \
		moc_imageViewer.obj \
		moc_thumbView.obj \
		moc_inSituView.obj \
		moc_ishTextEntry.obj \
		moc_ishFloatEntry.obj \
		moc_ishAnnotationEditor.obj \
		moc_ishAnnotationErrorMessage.obj \
		moc_textWidget.obj \
		moc_pointDrawer.obj \
		moc_distanceViewer.obj \
		moc_tdPointDrawer.obj \
		moc_traceDrawer.obj \
		moc_traceViewer.obj \
		moc_stressPlotter.obj \
		moc_fSpinBox.obj \
		moc_lSpinBox.obj \
		moc_compareController.obj \
		moc_protocolStepWidget.obj \
		moc_protocolViewer.obj \
		moc_protocolHolder.obj \
		moc_protocolManager.obj \
		moc_protocolClipboard.obj \
		moc_experimentBrowser.obj \
		moc_experimentMaker.obj \
		moc_imageAdder.obj \
		moc_fieldCreator.obj \
		moc_commentAdder.obj \
		moc_indexWidget.obj \
		moc_historyWidget.obj \
		moc_2dplot.obj \
		moc_chipSelection.obj \
		moc_chipChooser.obj \
		moc_exportMeanDialog.obj \
		moc_exportWidget.obj \
		moc_psDialog.obj \
		moc_fileDialog.obj \
		moc_sampleInfoWidget.obj
DIST	=	
TARGET	=	client_2.12.exe

####### Implicit rules

.SUFFIXES: .c .cpp .cc .cxx .C

.cpp.obj:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o$@ $<

.cc.obj:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o$@ $<

.cxx.obj:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o$@ $<

.C.obj:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o$@ $<

.c.obj:
	$(CC) -c $(CFLAGS) $(INCPATH) -o$@ $<

####### Build rules

all:  $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC) 
	$(LINK) @&&|
	$(LFLAGS) $(OBJECTS) $(OBJMOC),$(TARGET),,$(LIBS),$(DEF_FILE),$(RES_FILE)
|


mocables: $(SRCMOC)

Makefile: client.pro  $(QTDIR)\mkspecs\win32-borland\qmake.conf 
	$(QMAKE) -o Makefile client.pro
qmake: 
	@$(QMAKE) -o Makefile client.pro

dist:
	$(ZIP) .zip .pro $(SOURCES) $(HEADERS) $(DIST) $(FORMS)

clean:
	-del client.obj
	-del clientWindow.obj
	-del main.obj
	-del probe_set.obj
	-del stat.obj
	-del kernelFunction.obj
	-del twoDimDist.obj
	-del pointPlotter.obj
	-del expressionplotter.obj
	-del socketReadFunctions.obj
	-del dataView.obj
	-del dbQuerier.obj
	-del plotWindow.obj
	-del comparisonwindow.obj
	-del compInputWindow.obj
	-del smallToggle.obj
	-del listWindow.obj
	-del probeSetWidget.obj
	-del meanPlotWindow.obj
	-del meanExpressionPlotter.obj
	-del keyWindow.obj
	-del exptinfo.obj
	-del experimentWidget.obj
	-del experimentChooser.obj
	-del sampleMemoryWidget.obj
	-del sampleSelectionWidget.obj
	-del orderWidget.obj
	-del orderWindow.obj
	-del bytevec.obj
	-del logindialog.obj
	-del passwdchange.obj
	-del blastalignpainter.obj
	-del blastAlignWidget.obj
	-del glPlotter.obj
	-del statWidget.obj
	-del statWindow.obj
	-del distChooser.obj
	-del twoDimDistLauncher.obj
	-del twoDimDistPlotter.obj
	-del GenAlignWidget.obj
	-del annotator.obj
	-del newSession.obj
	-del sessionWidget.obj
	-del sessionManager.obj
	-del annotationWidget.obj
	-del annotationViewer.obj
	-del genAlignView.obj
	-del sequenceRequest.obj
	-del seqWidget.obj
	-del clusterWindow.obj
	-del clusterListItem.obj
	-del clusterPlotter.obj
	-del regionListItem.obj
	-del regionWindow.obj
	-del localRegionWidget.obj
	-del localRegionView.obj
	-del jpgView.obj
	-del imageViewer.obj
	-del thumbView.obj
	-del inSituView.obj
	-del ishTextEntry.obj
	-del ishFloatEntry.obj
	-del ishAnnotationEditor.obj
	-del ishAnnotationErrorMessage.obj
	-del textWidget.obj
	-del distanceMapper.obj
	-del pointDrawer.obj
	-del distanceViewer.obj
	-del tdPointDrawer.obj
	-del traceDrawer.obj
	-del traceViewer.obj
	-del stressPlotter.obj
	-del fSpinBox.obj
	-del lSpinBox.obj
	-del compareController.obj
	-del dataStructs.obj
	-del protocolStepWidget.obj
	-del protocolViewer.obj
	-del protocolHolder.obj
	-del protocolManager.obj
	-del protocolClipboard.obj
	-del experimentBrowser.obj
	-del experimentMaker.obj
	-del imageAdder.obj
	-del fieldCreator.obj
	-del commentAdder.obj
	-del indexWidget.obj
	-del historyWidget.obj
	-del boolParser.obj
	-del 2dplot.obj
	-del chipSelection.obj
	-del chipChooser.obj
	-del exportMeanDialog.obj
	-del exportWidget.obj
	-del psDialog.obj
	-del fileDialog.obj
	-del sampleInfoWidget.obj
	-del moc_client.cpp
	-del moc_clientWindow.cpp
	-del stat\moc_pointPlotter.cpp
	-del moc_expressionplotter.cpp
	-del moc_dataView.cpp
	-del moc_dbQuerier.cpp
	-del moc_plotWindow.cpp
	-del comparisonWindow\moc_comparisonwindow.cpp
	-del comparisonWindow\moc_compInputWindow.cpp
	-del smallToggle\moc_smallToggle.cpp
	-del listWindow\moc_listWindow.cpp
	-del probeSetWidget\moc_probeSetWidget.cpp
	-del meanPlotWindow\moc_meanPlotWindow.cpp
	-del meanPlotWindow\moc_meanExpressionPlotter.cpp
	-del meanPlotWindow\moc_keyWindow.cpp
	-del experimentWidget\moc_experimentWidget.cpp
	-del experimentChooser\moc_experimentChooser.cpp
	-del experimentChooser\moc_sampleMemoryWidget.cpp
	-del experimentChooser\moc_sampleSelectionWidget.cpp
	-del experimentChooser\orderChooser\moc_orderWindow.cpp
	-del experimentChooser\orderChooser\moc_orderWidget.cpp
	-del logindialog\moc_logindialog.cpp
	-del passwdchange\moc_passwdchange.cpp
	-del blastAlignPainter\moc_blastalignpainter.cpp
	-del blastAlignPainter\moc_blastAlignWidget.cpp
	-del glPlotter\moc_glPlotter.cpp
	-del statPlotter\moc_statWidget.cpp
	-del statPlotter\moc_statWindow.cpp
	-del statPlotter\moc_distChooser.cpp
	-del statPlotter\moc_twoDimDistLauncher.cpp
	-del statPlotter\moc_twoDimDistPlotter.cpp
	-del blastAlignPainter\moc_GenAlignWidget.cpp
	-del annotator\moc_annotator.cpp
	-del annotator\moc_newSession.cpp
	-del annotator\sessionManager\moc_sessionWidget.cpp
	-del annotator\sessionManager\moc_sessionManager.cpp
	-del annotator\annotationWidget\moc_annotationWidget.cpp
	-del annotator\moc_annotationViewer.cpp
	-del blastAlignPainter\moc_genAlignView.cpp
	-del sequence\moc_seqWidget.cpp
	-del clusterWindow\moc_clusterWindow.cpp
	-del clusterWindow\moc_clusterPlotter.cpp
	-del genomicRegion\moc_regionWindow.cpp
	-del genomicRegion\moc_localRegionWidget.cpp
	-del genomicRegion\moc_localRegionView.cpp
	-del jpgView\moc_jpgView.cpp
	-del jpgView\moc_imageViewer.cpp
	-del jpgView\moc_thumbView.cpp
	-del jpgView\moc_inSituView.cpp
	-del jpgView\moc_ishTextEntry.cpp
	-del jpgView\moc_ishFloatEntry.cpp
	-del jpgView\moc_ishAnnotationEditor.cpp
	-del jpgView\moc_ishAnnotationErrorMessage.cpp
	-del jpgView\moc_textWidget.cpp
	-del distanceMapper\moc_pointDrawer.cpp
	-del distanceMapper\moc_distanceViewer.cpp
	-del distanceMapper\moc_tdPointDrawer.cpp
	-del distanceMapper\moc_traceDrawer.cpp
	-del distanceMapper\moc_traceViewer.cpp
	-del distanceMapper\moc_stressPlotter.cpp
	-del customWidgets\moc_fSpinBox.cpp
	-del customWidgets\moc_lSpinBox.cpp
	-del distanceMapper\moc_compareController.cpp
	-del protocol\moc_protocolStepWidget.cpp
	-del protocol\moc_protocolViewer.cpp
	-del protocol\moc_protocolHolder.cpp
	-del protocol\moc_protocolManager.cpp
	-del protocol\moc_protocolClipboard.cpp
	-del experiment\moc_experimentBrowser.cpp
	-del experiment\moc_experimentMaker.cpp
	-del jpgView\moc_imageAdder.cpp
	-del jpgView\moc_fieldCreator.cpp
	-del jpgView\moc_commentAdder.cpp
	-del indexHistory\moc_indexWidget.cpp
	-del indexHistory\moc_historyWidget.cpp
	-del 2dplot\moc_2dplot.cpp
	-del chips\moc_chipSelection.cpp
	-del chips\moc_chipChooser.cpp
	-del dialogs\moc_exportMeanDialog.cpp
	-del exportWindow\moc_exportWidget.cpp
	-del exportWindow\moc_psDialog.cpp
	-del exportWindow\moc_fileDialog.cpp
	-del sampleInfo\moc_sampleInfoWidget.cpp
	-del moc_client.obj
	-del moc_clientWindow.obj
	-del moc_pointPlotter.obj
	-del moc_expressionplotter.obj
	-del moc_dataView.obj
	-del moc_dbQuerier.obj
	-del moc_plotWindow.obj
	-del moc_comparisonwindow.obj
	-del moc_compInputWindow.obj
	-del moc_smallToggle.obj
	-del moc_listWindow.obj
	-del moc_probeSetWidget.obj
	-del moc_meanPlotWindow.obj
	-del moc_meanExpressionPlotter.obj
	-del moc_keyWindow.obj
	-del moc_experimentWidget.obj
	-del moc_experimentChooser.obj
	-del moc_sampleMemoryWidget.obj
	-del moc_sampleSelectionWidget.obj
	-del moc_orderWindow.obj
	-del moc_orderWidget.obj
	-del moc_logindialog.obj
	-del moc_passwdchange.obj
	-del moc_blastalignpainter.obj
	-del moc_blastAlignWidget.obj
	-del moc_glPlotter.obj
	-del moc_statWidget.obj
	-del moc_statWindow.obj
	-del moc_distChooser.obj
	-del moc_twoDimDistLauncher.obj
	-del moc_twoDimDistPlotter.obj
	-del moc_GenAlignWidget.obj
	-del moc_annotator.obj
	-del moc_newSession.obj
	-del moc_sessionWidget.obj
	-del moc_sessionManager.obj
	-del moc_annotationWidget.obj
	-del moc_annotationViewer.obj
	-del moc_genAlignView.obj
	-del moc_seqWidget.obj
	-del moc_clusterWindow.obj
	-del moc_clusterPlotter.obj
	-del moc_regionWindow.obj
	-del moc_localRegionWidget.obj
	-del moc_localRegionView.obj
	-del moc_jpgView.obj
	-del moc_imageViewer.obj
	-del moc_thumbView.obj
	-del moc_inSituView.obj
	-del moc_ishTextEntry.obj
	-del moc_ishFloatEntry.obj
	-del moc_ishAnnotationEditor.obj
	-del moc_ishAnnotationErrorMessage.obj
	-del moc_textWidget.obj
	-del moc_pointDrawer.obj
	-del moc_distanceViewer.obj
	-del moc_tdPointDrawer.obj
	-del moc_traceDrawer.obj
	-del moc_traceViewer.obj
	-del moc_stressPlotter.obj
	-del moc_fSpinBox.obj
	-del moc_lSpinBox.obj
	-del moc_compareController.obj
	-del moc_protocolStepWidget.obj
	-del moc_protocolViewer.obj
	-del moc_protocolHolder.obj
	-del moc_protocolManager.obj
	-del moc_protocolClipboard.obj
	-del moc_experimentBrowser.obj
	-del moc_experimentMaker.obj
	-del moc_imageAdder.obj
	-del moc_fieldCreator.obj
	-del moc_commentAdder.obj
	-del moc_indexWidget.obj
	-del moc_historyWidget.obj
	-del moc_2dplot.obj
	-del moc_chipSelection.obj
	-del moc_chipChooser.obj
	-del moc_exportMeanDialog.obj
	-del moc_exportWidget.obj
	-del moc_psDialog.obj
	-del moc_fileDialog.obj
	-del moc_sampleInfoWidget.obj
	-del client_2.12.tds

distclean: clean
	-del $(TARGET)

####### Compile

client.obj: client.cpp client.h \
		probe_set\probe_set.h \
		bytevec\bytevec.h \
		exptinfo.h \
		annotator\sessionManager\sessionWidget.h \
		sequence\sequenceRequest.h \
		stat\stat.h \
		dataStructs.h \
		chips\chipSelection.h \
		sequence\seqWidget.h

clientWindow.obj: clientWindow.cpp clientWindow.h \
		client.h \
		experimentChooser\experimentChooser.h \
		plotWindow.h \
		dataView.h \
		probe_set\probe_set.h \
		exptinfo.h \
		comparisonWindow\comparisonwindow.h \
		listWindow\listWindow.h \
		probeSetWidget\probeSetWidget.h \
		meanPlotWindow\meanPlotWindow.h \
		logindialog\logindialog.h \
		passwdchange\passwdchange.h \
		statPlotter\statWindow.h \
		annotator\annotator.h \
		annotator\sessionManager\sessionWidget.h \
		sequence\sequenceRequest.h \
		clusterWindow\clusterWindow.h \
		genomicRegion\regionWindow.h \
		indexHistory\historyWidget.h \
		dataStructs.h \
		chips\chipChooser.h \
		chips\chipSelection.h \
		protocol\protocolManager.h \
		sampleInfo\sampleInfoWidget.h \
		dbQuerier.h \
		jpgView\inSituView.h \
		distanceMapper\compareController.h \
		customWidgets\lSpinBox.h \
		dialogs\exportMeanDialog.h \
		bytevec\bytevec.h \
		sequence\seqWidget.h \
		expressionplotter.h \
		2dplot\2dplot.h \
		glPlotter\glPlotter.h \
		stat\pointPlotter.h \
		exportWindow\exportWidget.h \
		exportWindow\psDialog.h \
		exportWindow\fileDialog.h \
		annotator\annotationViewer.h \
		blastAlignPainter\blastAlignWidget.h \
		blastAlignPainter\GenAlignWidget.h \
		blastAlignPainter\genAlignView.h \
		genomicRegion\localRegionView.h \
		annotator\annotationWidget\annotationWidget.h \
		blastAlignPainter\blastalignpainter.h \
		genomicRegion\localRegionWidget.h \
		jpgView\imageViewer.h \
		experiment\experimentBrowser.h \
		jpgView\ishAnnotationEditor.h \
		jpgView\imageAdder.h \
		jpgView\thumbView.h \
		jpgView\jpgView.h \
		experiment\experimentMaker.h \
		protocol\protocolHolder.h \
		protocol\protocolClipboard.h \
		protocol\protocolViewer.h \
		protocol\protocolStepWidget.h \
		jpgView\textWidget.h \
		jpgView\ishTextEntry.h \
		jpgView\ishFloatEntry.h \
		jpgView\fieldCreator.h \
		jpgView\commentAdder.h \
		experimentWidget\experimentWidget.h \
		experimentChooser\orderChooser\orderWindow.h \
		experimentChooser\sampleMemoryWidget.h \
		smallToggle\smallToggle.h \
		experimentChooser\orderChooser\orderWidget.h \
		experimentChooser\sampleSelectionWidget.h \
		comparisonWindow\compInputWindow.h \
		meanPlotWindow\meanExpressionPlotter.h \
		meanPlotWindow\keyWindow.h \
		statPlotter\statWidget.h \
		statPlotter\distChooser.h \
		statPlotter\twoDimDistLauncher.h \
		stat\twoDimDist.h \
		statPlotter\twoDimDistPlotter.h \
		stat\kernelFunction.h \
		annotator\newSession.h \
		annotator\sessionManager\sessionManager.h \
		clusterWindow\clusterPlotter.h \
		distanceMapper\distanceViewer.h \
		customWidgets\fSpinBox.h \
		distanceMapper\traceViewer.h \
		distanceMapper\distanceMapper.h \
		distanceMapper\pointDrawer.h \
		distanceMapper\stressPlotter.h \
		distanceMapper\tdPointDrawer.h \
		distanceMapper\traceDrawer.h \
		indexHistory\indexWidget.h

main.obj: main.cpp clientWindow.h \
		client.h \
		exptinfo.h \
		plotWindow.h \
		sampleInfo\sampleInfoWidget.h \
		probe_set\probe_set.h \
		dbQuerier.h \
		dataView.h \
		jpgView\inSituView.h \
		experimentChooser\experimentChooser.h \
		comparisonWindow\comparisonwindow.h \
		listWindow\listWindow.h \
		probeSetWidget\probeSetWidget.h \
		meanPlotWindow\meanPlotWindow.h \
		passwdchange\passwdchange.h \
		statPlotter\statWindow.h \
		annotator\annotator.h \
		clusterWindow\clusterWindow.h \
		genomicRegion\regionWindow.h \
		distanceMapper\compareController.h \
		protocol\protocolManager.h \
		customWidgets\lSpinBox.h \
		dialogs\exportMeanDialog.h \
		dataStructs.h \
		chips\chipSelection.h \
		bytevec\bytevec.h \
		annotator\sessionManager\sessionWidget.h \
		sequence\sequenceRequest.h \
		sequence\seqWidget.h \
		expressionplotter.h \
		2dplot\2dplot.h \
		glPlotter\glPlotter.h \
		stat\pointPlotter.h \
		exportWindow\exportWidget.h \
		exportWindow\psDialog.h \
		exportWindow\fileDialog.h \
		annotator\annotationViewer.h \
		blastAlignPainter\blastAlignWidget.h \
		blastAlignPainter\GenAlignWidget.h \
		blastAlignPainter\genAlignView.h \
		genomicRegion\localRegionView.h \
		annotator\annotationWidget\annotationWidget.h \
		blastAlignPainter\blastalignpainter.h \
		genomicRegion\localRegionWidget.h \
		jpgView\imageViewer.h \
		experiment\experimentBrowser.h \
		jpgView\ishAnnotationEditor.h \
		jpgView\imageAdder.h \
		jpgView\thumbView.h \
		jpgView\jpgView.h \
		experiment\experimentMaker.h \
		protocol\protocolHolder.h \
		protocol\protocolClipboard.h \
		protocol\protocolViewer.h \
		protocol\protocolStepWidget.h \
		jpgView\textWidget.h \
		jpgView\ishTextEntry.h \
		jpgView\ishFloatEntry.h \
		jpgView\fieldCreator.h \
		jpgView\commentAdder.h \
		experimentWidget\experimentWidget.h \
		experimentChooser\orderChooser\orderWindow.h \
		experimentChooser\sampleMemoryWidget.h \
		smallToggle\smallToggle.h \
		experimentChooser\orderChooser\orderWidget.h \
		experimentChooser\sampleSelectionWidget.h \
		comparisonWindow\compInputWindow.h \
		meanPlotWindow\meanExpressionPlotter.h \
		meanPlotWindow\keyWindow.h \
		statPlotter\statWidget.h \
		statPlotter\distChooser.h \
		statPlotter\twoDimDistLauncher.h \
		stat\twoDimDist.h \
		statPlotter\twoDimDistPlotter.h \
		stat\kernelFunction.h \
		annotator\newSession.h \
		annotator\sessionManager\sessionManager.h \
		clusterWindow\clusterPlotter.h \
		distanceMapper\distanceViewer.h \
		customWidgets\fSpinBox.h \
		distanceMapper\traceViewer.h \
		distanceMapper\distanceMapper.h \
		distanceMapper\pointDrawer.h \
		distanceMapper\stressPlotter.h \
		distanceMapper\tdPointDrawer.h \
		distanceMapper\traceDrawer.h

probe_set.obj: probe_set\probe_set.cpp probe_set\require.h \
		probe_set\probe_set.h \
		stat\stat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -oprobe_set.obj probe_set\probe_set.cpp

stat.obj: stat\stat.cpp stat\stat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -ostat.obj stat\stat.cpp

kernelFunction.obj: stat\kernelFunction.cpp stat\kernelFunction.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -okernelFunction.obj stat\kernelFunction.cpp

twoDimDist.obj: stat\twoDimDist.cpp stat\twoDimDist.h \
		stat\kernelFunction.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -otwoDimDist.obj stat\twoDimDist.cpp

pointPlotter.obj: stat\pointPlotter.cpp stat\pointPlotter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -opointPlotter.obj stat\pointPlotter.cpp

expressionplotter.obj: expressionplotter.cpp expressionplotter.h

socketReadFunctions.obj: socketReadFunctions.cpp socketReadFunctions.h

dataView.obj: dataView.cpp dataView.h \
		probe_set\probe_set.h \
		blastAlignPainter\blastAlignWidget.h \
		blastAlignPainter\GenAlignWidget.h \
		sequence\sequenceRequest.h \
		genomicRegion\localRegionView.h \
		exptinfo.h \
		client.h \
		annotator\annotationViewer.h \
		blastAlignPainter\genAlignView.h \
		dataStructs.h \
		chips\chipSelection.h \
		bytevec\bytevec.h \
		annotator\sessionManager\sessionWidget.h \
		sequence\seqWidget.h \
		annotator\annotationWidget\annotationWidget.h \
		blastAlignPainter\blastalignpainter.h \
		genomicRegion\localRegionWidget.h

dbQuerier.obj: dbQuerier.cpp dbQuerier.h

plotWindow.obj: plotWindow.cpp plotWindow.h \
		probe_set\probe_set.h \
		stat\stat.h \
		glPlotter\glPlotter.h \
		expressionplotter.h \
		2dplot\2dplot.h \
		dataStructs.h \
		stat\pointPlotter.h \
		exportWindow\exportWidget.h \
		exportWindow\psDialog.h \
		exportWindow\fileDialog.h

comparisonwindow.obj: comparisonWindow\comparisonwindow.cpp comparisonWindow\comparisonwindow.h \
		smallToggle\smallToggle.h \
		stat\stat.h \
		exptinfo.h \
		comparisonWindow\compInputWindow.h \
		dataStructs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -ocomparisonwindow.obj comparisonWindow\comparisonwindow.cpp

compInputWindow.obj: comparisonWindow\compInputWindow.cpp dataStructs.h \
		comparisonWindow\compInputWindow.h \
		exptinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -ocompInputWindow.obj comparisonWindow\compInputWindow.cpp

smallToggle.obj: smallToggle\smallToggle.cpp smallToggle\smallToggle.h \
		images.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -osmallToggle.obj smallToggle\smallToggle.cpp

listWindow.obj: listWindow\listWindow.cpp listWindow\listWindow.h \
		probeSetWidget\probeSetWidget.h \
		probe_set\probe_set.h \
		smallToggle\smallToggle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -olistWindow.obj listWindow\listWindow.cpp

probeSetWidget.obj: probeSetWidget\probeSetWidget.cpp probeSetWidget\probeSetWidget.h \
		smallToggle\smallToggle.h \
		probe_set\probe_set.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -oprobeSetWidget.obj probeSetWidget\probeSetWidget.cpp

meanPlotWindow.obj: meanPlotWindow\meanPlotWindow.cpp meanPlotWindow\meanPlotWindow.h \
		probeSetWidget\probeSetWidget.h \
		meanPlotWindow\meanExpressionPlotter.h \
		meanPlotWindow\keyWindow.h \
		stat\stat.h \
		exptinfo.h \
		probe_set\probe_set.h \
		smallToggle\smallToggle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omeanPlotWindow.obj meanPlotWindow\meanPlotWindow.cpp

meanExpressionPlotter.obj: meanPlotWindow\meanExpressionPlotter.cpp meanPlotWindow\meanExpressionPlotter.h \
		exptinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omeanExpressionPlotter.obj meanPlotWindow\meanExpressionPlotter.cpp

keyWindow.obj: meanPlotWindow\keyWindow.cpp meanPlotWindow\keyWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -okeyWindow.obj meanPlotWindow\keyWindow.cpp

exptinfo.obj: exptinfo.cpp exptinfo.h

experimentWidget.obj: experimentWidget\experimentWidget.cpp experimentWidget\experimentWidget.h \
		exptinfo.h \
		smallToggle\smallToggle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -oexperimentWidget.obj experimentWidget\experimentWidget.cpp

experimentChooser.obj: experimentChooser\experimentChooser.cpp experimentChooser\experimentChooser.h \
		exptinfo.h \
		experimentWidget\experimentWidget.h \
		experimentChooser\orderChooser\orderWindow.h \
		experimentChooser\sampleMemoryWidget.h \
		smallToggle\smallToggle.h \
		experimentChooser\orderChooser\orderWidget.h \
		dataStructs.h \
		experimentChooser\sampleSelectionWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -oexperimentChooser.obj experimentChooser\experimentChooser.cpp

sampleMemoryWidget.obj: experimentChooser\sampleMemoryWidget.cpp experimentChooser\sampleMemoryWidget.h \
		experimentChooser\sampleSelectionWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -osampleMemoryWidget.obj experimentChooser\sampleMemoryWidget.cpp

sampleSelectionWidget.obj: experimentChooser\sampleSelectionWidget.cpp experimentChooser\sampleSelectionWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -osampleSelectionWidget.obj experimentChooser\sampleSelectionWidget.cpp

orderWidget.obj: experimentChooser\orderChooser\orderWidget.cpp experimentChooser\orderChooser\orderWidget.h \
		exptinfo.h \
		dataStructs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -oorderWidget.obj experimentChooser\orderChooser\orderWidget.cpp

orderWindow.obj: experimentChooser\orderChooser\orderWindow.cpp experimentChooser\orderChooser\orderWindow.h \
		smallToggle\smallToggle.h \
		stat\stat.h \
		exptinfo.h \
		experimentChooser\orderChooser\orderWidget.h \
		dataStructs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -oorderWindow.obj experimentChooser\orderChooser\orderWindow.cpp

bytevec.obj: bytevec\bytevec.cpp bytevec\bytevec.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -obytevec.obj bytevec\bytevec.cpp

logindialog.obj: logindialog\logindialog.cpp logindialog\logindialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -ologindialog.obj logindialog\logindialog.cpp

passwdchange.obj: passwdchange\passwdchange.cpp passwdchange\passwdchange.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -opasswdchange.obj passwdchange\passwdchange.cpp

blastalignpainter.obj: blastAlignPainter\blastalignpainter.cpp blastAlignPainter\blastalignpainter.h \
		probe_set\probe_set.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -oblastalignpainter.obj blastAlignPainter\blastalignpainter.cpp

blastAlignWidget.obj: blastAlignPainter\blastAlignWidget.cpp blastAlignPainter\blastalignpainter.h \
		blastAlignPainter\blastAlignWidget.h \
		probe_set\probe_set.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -oblastAlignWidget.obj blastAlignPainter\blastAlignWidget.cpp

glPlotter.obj: glPlotter\glPlotter.cpp glPlotter\glPlotter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -oglPlotter.obj glPlotter\glPlotter.cpp

statWidget.obj: statPlotter\statWidget.cpp statPlotter\statWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -ostatWidget.obj statPlotter\statWidget.cpp

statWindow.obj: statPlotter\statWindow.cpp statPlotter\statWidget.h \
		statPlotter\statWindow.h \
		statPlotter\distChooser.h \
		probe_set\probe_set.h \
		statPlotter\twoDimDistLauncher.h \
		stat\twoDimDist.h \
		statPlotter\twoDimDistPlotter.h \
		stat\kernelFunction.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -ostatWindow.obj statPlotter\statWindow.cpp

distChooser.obj: statPlotter\distChooser.cpp statPlotter\distChooser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -odistChooser.obj statPlotter\distChooser.cpp

twoDimDistLauncher.obj: statPlotter\twoDimDistLauncher.cpp statPlotter\twoDimDistLauncher.h \
		probe_set\probe_set.h \
		stat\twoDimDist.h \
		statPlotter\twoDimDistPlotter.h \
		stat\kernelFunction.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -otwoDimDistLauncher.obj statPlotter\twoDimDistLauncher.cpp

twoDimDistPlotter.obj: statPlotter\twoDimDistPlotter.cpp statPlotter\twoDimDistPlotter.h \
		stat\twoDimDist.h \
		stat\kernelFunction.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -otwoDimDistPlotter.obj statPlotter\twoDimDistPlotter.cpp

GenAlignWidget.obj: blastAlignPainter\GenAlignWidget.cpp blastAlignPainter\GenAlignWidget.h \
		probe_set\probe_set.h \
		sequence\sequenceRequest.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -oGenAlignWidget.obj blastAlignPainter\GenAlignWidget.cpp

annotator.obj: annotator\annotator.cpp annotator\newSession.h \
		annotator\annotator.h \
		annotator\sessionManager\sessionManager.h \
		annotator\sessionManager\sessionWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -oannotator.obj annotator\annotator.cpp

newSession.obj: annotator\newSession.cpp annotator\newSession.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -onewSession.obj annotator\newSession.cpp

sessionWidget.obj: annotator\sessionManager\sessionWidget.cpp annotator\sessionManager\sessionWidget.h \
		smallToggle\smallToggle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -osessionWidget.obj annotator\sessionManager\sessionWidget.cpp

sessionManager.obj: annotator\sessionManager\sessionManager.cpp annotator\sessionManager\sessionManager.h \
		annotator\sessionManager\sessionWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -osessionManager.obj annotator\sessionManager\sessionManager.cpp

annotationWidget.obj: annotator\annotationWidget\annotationWidget.cpp annotator\annotationWidget\annotationWidget.h \
		smallToggle\smallToggle.h \
		probe_set\probe_set.h \
		client.h \
		dataStructs.h \
		chips\chipSelection.h \
		bytevec\bytevec.h \
		exptinfo.h \
		annotator\sessionManager\sessionWidget.h \
		sequence\sequenceRequest.h \
		sequence\seqWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -oannotationWidget.obj annotator\annotationWidget\annotationWidget.cpp

annotationViewer.obj: annotator\annotationViewer.cpp annotator\annotationViewer.h \
		probe_set\probe_set.h \
		annotator\annotationWidget\annotationWidget.h \
		client.h \
		dataStructs.h \
		chips\chipSelection.h \
		bytevec\bytevec.h \
		exptinfo.h \
		annotator\sessionManager\sessionWidget.h \
		sequence\sequenceRequest.h \
		sequence\seqWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -oannotationViewer.obj annotator\annotationViewer.cpp

genAlignView.obj: blastAlignPainter\genAlignView.cpp blastAlignPainter\genAlignView.h \
		probe_set\probe_set.h \
		sequence\sequenceRequest.h \
		blastAlignPainter\GenAlignWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -ogenAlignView.obj blastAlignPainter\genAlignView.cpp

sequenceRequest.obj: sequence\sequenceRequest.cpp sequence\sequenceRequest.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -osequenceRequest.obj sequence\sequenceRequest.cpp

seqWidget.obj: sequence\seqWidget.cpp sequence\seqWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -oseqWidget.obj sequence\seqWidget.cpp

clusterWindow.obj: clusterWindow\clusterWindow.cpp clusterWindow\clusterWindow.h \
		smallToggle\smallToggle.h \
		clusterWindow\clusterListItem.h \
		clusterWindow\clusterPlotter.h \
		client.h \
		meanPlotWindow\meanExpressionPlotter.h \
		dataStructs.h \
		chips\chipSelection.h \
		probe_set\probe_set.h \
		bytevec\bytevec.h \
		exptinfo.h \
		annotator\sessionManager\sessionWidget.h \
		sequence\sequenceRequest.h \
		sequence\seqWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -oclusterWindow.obj clusterWindow\clusterWindow.cpp

clusterListItem.obj: clusterWindow\clusterListItem.cpp clusterWindow\clusterListItem.h \
		client.h \
		dataStructs.h \
		chips\chipSelection.h \
		probe_set\probe_set.h \
		bytevec\bytevec.h \
		exptinfo.h \
		annotator\sessionManager\sessionWidget.h \
		sequence\sequenceRequest.h \
		sequence\seqWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -oclusterListItem.obj clusterWindow\clusterListItem.cpp

clusterPlotter.obj: clusterWindow\clusterPlotter.cpp clusterWindow\clusterPlotter.h \
		client.h \
		meanPlotWindow\meanExpressionPlotter.h \
		dataStructs.h \
		chips\chipSelection.h \
		probe_set\probe_set.h \
		bytevec\bytevec.h \
		exptinfo.h \
		annotator\sessionManager\sessionWidget.h \
		sequence\sequenceRequest.h \
		sequence\seqWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -oclusterPlotter.obj clusterWindow\clusterPlotter.cpp

regionListItem.obj: genomicRegion\regionListItem.cpp genomicRegion\regionListItem.h \
		client.h \
		dataStructs.h \
		chips\chipSelection.h \
		probe_set\probe_set.h \
		bytevec\bytevec.h \
		exptinfo.h \
		annotator\sessionManager\sessionWidget.h \
		sequence\sequenceRequest.h \
		sequence\seqWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -oregionListItem.obj genomicRegion\regionListItem.cpp

regionWindow.obj: genomicRegion\regionWindow.cpp genomicRegion\regionWindow.h \
		genomicRegion\regionListItem.h \
		client.h \
		dataStructs.h \
		chips\chipSelection.h \
		probe_set\probe_set.h \
		bytevec\bytevec.h \
		exptinfo.h \
		annotator\sessionManager\sessionWidget.h \
		sequence\sequenceRequest.h \
		sequence\seqWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -oregionWindow.obj genomicRegion\regionWindow.cpp

localRegionWidget.obj: genomicRegion\localRegionWidget.cpp genomicRegion\localRegionWidget.h \
		client.h \
		sequence\sequenceRequest.h \
		dataStructs.h \
		chips\chipSelection.h \
		probe_set\probe_set.h \
		bytevec\bytevec.h \
		exptinfo.h \
		annotator\sessionManager\sessionWidget.h \
		sequence\seqWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -olocalRegionWidget.obj genomicRegion\localRegionWidget.cpp

localRegionView.obj: genomicRegion\localRegionView.cpp genomicRegion\localRegionView.h \
		genomicRegion\localRegionWidget.h \
		client.h \
		sequence\sequenceRequest.h \
		dataStructs.h \
		chips\chipSelection.h \
		probe_set\probe_set.h \
		bytevec\bytevec.h \
		exptinfo.h \
		annotator\sessionManager\sessionWidget.h \
		sequence\seqWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -olocalRegionView.obj genomicRegion\localRegionView.cpp

jpgView.obj: jpgView\jpgView.cpp jpgView\jpgView.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -ojpgView.obj jpgView\jpgView.cpp

imageViewer.obj: jpgView\imageViewer.cpp jpgView\imageViewer.h \
		jpgView\thumbView.h \
		dataStructs.h \
		jpgView\jpgView.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -oimageViewer.obj jpgView\imageViewer.cpp

thumbView.obj: jpgView\thumbView.cpp jpgView\thumbView.h \
		jpgView\jpgView.h \
		dataStructs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -othumbView.obj jpgView\thumbView.cpp

inSituView.obj: jpgView\inSituView.cpp jpgView\inSituView.h \
		dataStructs.h \
		client.h \
		experiment\experimentBrowser.h \
		jpgView\imageViewer.h \
		jpgView\ishAnnotationEditor.h \
		genomicRegion\localRegionView.h \
		jpgView\imageAdder.h \
		genomicRegion\localRegionWidget.h \
		sequence\sequenceRequest.h \
		chips\chipSelection.h \
		probe_set\probe_set.h \
		bytevec\bytevec.h \
		exptinfo.h \
		annotator\sessionManager\sessionWidget.h \
		sequence\seqWidget.h \
		jpgView\thumbView.h \
		jpgView\jpgView.h \
		experiment\experimentMaker.h \
		protocol\protocolManager.h \
		protocol\protocolHolder.h \
		protocol\protocolClipboard.h \
		protocol\protocolViewer.h \
		protocol\protocolStepWidget.h \
		jpgView\textWidget.h \
		jpgView\ishTextEntry.h \
		jpgView\ishFloatEntry.h \
		jpgView\fieldCreator.h \
		jpgView\commentAdder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -oinSituView.obj jpgView\inSituView.cpp

ishTextEntry.obj: jpgView\ishTextEntry.cpp jpgView\ishTextEntry.h \
		dataStructs.h \
		jpgView\ishAnnotationErrorMessage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -oishTextEntry.obj jpgView\ishTextEntry.cpp

ishFloatEntry.obj: jpgView\ishFloatEntry.cpp jpgView\ishFloatEntry.h \
		dataStructs.h \
		jpgView\ishAnnotationErrorMessage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -oishFloatEntry.obj jpgView\ishFloatEntry.cpp

ishAnnotationEditor.obj: jpgView\ishAnnotationEditor.cpp jpgView\ishAnnotationEditor.h \
		jpgView\ishTextEntry.h \
		jpgView\ishFloatEntry.h \
		jpgView\textWidget.h \
		dataStructs.h \
		jpgView\ishAnnotationErrorMessage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -oishAnnotationEditor.obj jpgView\ishAnnotationEditor.cpp

ishAnnotationErrorMessage.obj: jpgView\ishAnnotationErrorMessage.cpp jpgView\ishAnnotationErrorMessage.h \
		jpgView\ishFloatEntry.h \
		jpgView\ishTextEntry.h \
		dataStructs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -oishAnnotationErrorMessage.obj jpgView\ishAnnotationErrorMessage.cpp

textWidget.obj: jpgView\textWidget.cpp jpgView\textWidget.h \
		dataStructs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -otextWidget.obj jpgView\textWidget.cpp

distanceMapper.obj: distanceMapper\distanceMapper.cpp distanceMapper\distanceMapper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -odistanceMapper.obj distanceMapper\distanceMapper.cpp

pointDrawer.obj: distanceMapper\pointDrawer.cpp distanceMapper\pointDrawer.h \
		distanceMapper\distanceMapper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -opointDrawer.obj distanceMapper\pointDrawer.cpp

distanceViewer.obj: distanceMapper\distanceViewer.cpp distanceMapper\distanceViewer.h \
		distanceMapper\distanceMapper.h \
		distanceMapper\pointDrawer.h \
		distanceMapper\tdPointDrawer.h \
		customWidgets\fSpinBox.h \
		distanceMapper\stressPlotter.h \
		dataStructs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -odistanceViewer.obj distanceMapper\distanceViewer.cpp

tdPointDrawer.obj: distanceMapper\tdPointDrawer.cpp distanceMapper\tdPointDrawer.h \
		distanceMapper\distanceMapper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -otdPointDrawer.obj distanceMapper\tdPointDrawer.cpp

traceDrawer.obj: distanceMapper\traceDrawer.cpp distanceMapper\traceDrawer.h \
		dataStructs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -otraceDrawer.obj distanceMapper\traceDrawer.cpp

traceViewer.obj: distanceMapper\traceViewer.cpp distanceMapper\traceViewer.h \
		dataStructs.h \
		distanceMapper\traceDrawer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -otraceViewer.obj distanceMapper\traceViewer.cpp

stressPlotter.obj: distanceMapper\stressPlotter.cpp distanceMapper\stressPlotter.h \
		distanceMapper\distanceMapper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -ostressPlotter.obj distanceMapper\stressPlotter.cpp

fSpinBox.obj: customWidgets\fSpinBox.cpp customWidgets\fSpinBox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -ofSpinBox.obj customWidgets\fSpinBox.cpp

lSpinBox.obj: customWidgets\lSpinBox.cpp customWidgets\lSpinBox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -olSpinBox.obj customWidgets\lSpinBox.cpp

compareController.obj: distanceMapper\compareController.cpp distanceMapper\compareController.h \
		distanceMapper\traceDrawer.h \
		distanceMapper\distanceViewer.h \
		customWidgets\fSpinBox.h \
		dataStructs.h \
		distanceMapper\traceViewer.h \
		distanceMapper\distanceMapper.h \
		distanceMapper\pointDrawer.h \
		distanceMapper\stressPlotter.h \
		distanceMapper\tdPointDrawer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -ocompareController.obj distanceMapper\compareController.cpp

dataStructs.obj: dataStructs.cpp dataStructs.h

protocolStepWidget.obj: protocol\protocolStepWidget.cpp protocol\protocolStepWidget.h \
		dataStructs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -oprotocolStepWidget.obj protocol\protocolStepWidget.cpp

protocolViewer.obj: protocol\protocolViewer.cpp protocol\protocolViewer.h \
		protocol\protocolStepWidget.h \
		protocol\protocolClipboard.h \
		dataStructs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -oprotocolViewer.obj protocol\protocolViewer.cpp

protocolHolder.obj: protocol\protocolHolder.cpp protocol\protocolHolder.h \
		dataStructs.h \
		protocol\protocolViewer.h \
		protocol\protocolClipboard.h \
		protocol\protocolStepWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -oprotocolHolder.obj protocol\protocolHolder.cpp

protocolManager.obj: protocol\protocolManager.cpp protocol\protocolManager.h \
		dataStructs.h \
		protocol\protocolHolder.h \
		protocol\protocolClipboard.h \
		protocol\protocolViewer.h \
		protocol\protocolStepWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -oprotocolManager.obj protocol\protocolManager.cpp

protocolClipboard.obj: protocol\protocolClipboard.cpp protocol\protocolClipboard.h \
		dataStructs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -oprotocolClipboard.obj protocol\protocolClipboard.cpp

experimentBrowser.obj: experiment\experimentBrowser.cpp experiment\experimentBrowser.h \
		experiment\experimentMaker.h \
		dataStructs.h \
		protocol\protocolManager.h \
		protocol\protocolHolder.h \
		protocol\protocolClipboard.h \
		protocol\protocolViewer.h \
		protocol\protocolStepWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -oexperimentBrowser.obj experiment\experimentBrowser.cpp

experimentMaker.obj: experiment\experimentMaker.cpp experiment\experimentMaker.h \
		protocol\protocolManager.h \
		dataStructs.h \
		protocol\protocolHolder.h \
		protocol\protocolClipboard.h \
		protocol\protocolViewer.h \
		protocol\protocolStepWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -oexperimentMaker.obj experiment\experimentMaker.cpp

imageAdder.obj: jpgView\imageAdder.cpp jpgView\imageAdder.h \
		dataStructs.h \
		jpgView\fieldCreator.h \
		jpgView\commentAdder.h \
		jpgView\jpgView.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -oimageAdder.obj jpgView\imageAdder.cpp

fieldCreator.obj: jpgView\fieldCreator.cpp jpgView\fieldCreator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -ofieldCreator.obj jpgView\fieldCreator.cpp

commentAdder.obj: jpgView\commentAdder.cpp jpgView\commentAdder.h \
		jpgView\fieldCreator.h \
		dataStructs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -ocommentAdder.obj jpgView\commentAdder.cpp

indexWidget.obj: indexHistory\indexWidget.cpp indexHistory\indexWidget.h \
		smallToggle\smallToggle.h \
		dataStructs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -oindexWidget.obj indexHistory\indexWidget.cpp

historyWidget.obj: indexHistory\historyWidget.cpp indexHistory\historyWidget.h \
		boolParser\boolParser.h \
		dataStructs.h \
		indexHistory\indexWidget.h \
		smallToggle\smallToggle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -ohistoryWidget.obj indexHistory\historyWidget.cpp

boolParser.obj: boolParser\boolParser.cpp boolParser\boolParser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -oboolParser.obj boolParser\boolParser.cpp

2dplot.obj: 2dplot\2dplot.cpp 2dplot\2dplot.h \
		stat\kernelFunction.h \
		dataStructs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o2dplot.obj 2dplot\2dplot.cpp

chipSelection.obj: chips\chipSelection.cpp chips\chipSelection.h \
		dataStructs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -ochipSelection.obj chips\chipSelection.cpp

chipChooser.obj: chips\chipChooser.cpp chips\chipChooser.h \
		chips\chipSelection.h \
		dataStructs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -ochipChooser.obj chips\chipChooser.cpp

exportMeanDialog.obj: dialogs\exportMeanDialog.cpp dialogs\exportMeanDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -oexportMeanDialog.obj dialogs\exportMeanDialog.cpp

exportWidget.obj: exportWindow\exportWidget.cpp exportWindow\exportWidget.h \
		expressionplotter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -oexportWidget.obj exportWindow\exportWidget.cpp

psDialog.obj: exportWindow\psDialog.cpp exportWindow\psDialog.h \
		exportWindow\exportWidget.h \
		exportWindow\fileDialog.h \
		expressionplotter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -opsDialog.obj exportWindow\psDialog.cpp

fileDialog.obj: exportWindow\fileDialog.cpp exportWindow\fileDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -ofileDialog.obj exportWindow\fileDialog.cpp

sampleInfoWidget.obj: sampleInfo\sampleInfoWidget.cpp sampleInfo\sampleInfoWidget.h \
		exptinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -osampleInfoWidget.obj sampleInfo\sampleInfoWidget.cpp

moc_client.obj: moc_client.cpp client.h dataStructs.h \
		chips\chipSelection.h \
		probe_set\probe_set.h \
		bytevec\bytevec.h \
		exptinfo.h \
		annotator\sessionManager\sessionWidget.h \
		sequence\sequenceRequest.h \
		sequence\seqWidget.h

moc_clientWindow.obj: moc_clientWindow.cpp clientWindow.h client.h \
		exptinfo.h \
		plotWindow.h \
		sampleInfo\sampleInfoWidget.h \
		probe_set\probe_set.h \
		dbQuerier.h \
		dataView.h \
		jpgView\inSituView.h \
		experimentChooser\experimentChooser.h \
		comparisonWindow\comparisonwindow.h \
		listWindow\listWindow.h \
		probeSetWidget\probeSetWidget.h \
		meanPlotWindow\meanPlotWindow.h \
		passwdchange\passwdchange.h \
		statPlotter\statWindow.h \
		annotator\annotator.h \
		clusterWindow\clusterWindow.h \
		genomicRegion\regionWindow.h \
		distanceMapper\compareController.h \
		protocol\protocolManager.h \
		customWidgets\lSpinBox.h \
		dialogs\exportMeanDialog.h \
		dataStructs.h \
		chips\chipSelection.h \
		bytevec\bytevec.h \
		annotator\sessionManager\sessionWidget.h \
		sequence\sequenceRequest.h \
		sequence\seqWidget.h \
		expressionplotter.h \
		2dplot\2dplot.h \
		glPlotter\glPlotter.h \
		stat\pointPlotter.h \
		exportWindow\exportWidget.h \
		exportWindow\psDialog.h \
		exportWindow\fileDialog.h \
		annotator\annotationViewer.h \
		blastAlignPainter\blastAlignWidget.h \
		blastAlignPainter\GenAlignWidget.h \
		blastAlignPainter\genAlignView.h \
		genomicRegion\localRegionView.h \
		annotator\annotationWidget\annotationWidget.h \
		blastAlignPainter\blastalignpainter.h \
		genomicRegion\localRegionWidget.h \
		jpgView\imageViewer.h \
		experiment\experimentBrowser.h \
		jpgView\ishAnnotationEditor.h \
		jpgView\imageAdder.h \
		jpgView\thumbView.h \
		jpgView\jpgView.h \
		experiment\experimentMaker.h \
		protocol\protocolHolder.h \
		protocol\protocolClipboard.h \
		protocol\protocolViewer.h \
		protocol\protocolStepWidget.h \
		jpgView\textWidget.h \
		jpgView\ishTextEntry.h \
		jpgView\ishFloatEntry.h \
		jpgView\fieldCreator.h \
		jpgView\commentAdder.h \
		experimentWidget\experimentWidget.h \
		experimentChooser\orderChooser\orderWindow.h \
		experimentChooser\sampleMemoryWidget.h \
		smallToggle\smallToggle.h \
		experimentChooser\orderChooser\orderWidget.h \
		experimentChooser\sampleSelectionWidget.h \
		comparisonWindow\compInputWindow.h \
		meanPlotWindow\meanExpressionPlotter.h \
		meanPlotWindow\keyWindow.h \
		statPlotter\statWidget.h \
		statPlotter\distChooser.h \
		statPlotter\twoDimDistLauncher.h \
		stat\twoDimDist.h \
		statPlotter\twoDimDistPlotter.h \
		stat\kernelFunction.h \
		annotator\newSession.h \
		annotator\sessionManager\sessionManager.h \
		clusterWindow\clusterPlotter.h \
		distanceMapper\distanceViewer.h \
		customWidgets\fSpinBox.h \
		distanceMapper\traceViewer.h \
		distanceMapper\distanceMapper.h \
		distanceMapper\pointDrawer.h \
		distanceMapper\stressPlotter.h \
		distanceMapper\tdPointDrawer.h \
		distanceMapper\traceDrawer.h

moc_pointPlotter.obj: stat\moc_pointPlotter.cpp stat\pointPlotter.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_pointPlotter.obj stat\moc_pointPlotter.cpp

moc_expressionplotter.obj: moc_expressionplotter.cpp expressionplotter.h 

moc_dataView.obj: moc_dataView.cpp dataView.h exptinfo.h \
		probe_set\probe_set.h \
		client.h \
		sequence\sequenceRequest.h \
		annotator\annotationViewer.h \
		blastAlignPainter\blastAlignWidget.h \
		blastAlignPainter\GenAlignWidget.h \
		blastAlignPainter\genAlignView.h \
		genomicRegion\localRegionView.h \
		dataStructs.h \
		chips\chipSelection.h \
		bytevec\bytevec.h \
		annotator\sessionManager\sessionWidget.h \
		sequence\seqWidget.h \
		annotator\annotationWidget\annotationWidget.h \
		blastAlignPainter\blastalignpainter.h \
		genomicRegion\localRegionWidget.h

moc_dbQuerier.obj: moc_dbQuerier.cpp dbQuerier.h 

moc_plotWindow.obj: moc_plotWindow.cpp plotWindow.h expressionplotter.h \
		2dplot\2dplot.h \
		dataStructs.h \
		probe_set\probe_set.h \
		glPlotter\glPlotter.h \
		stat\pointPlotter.h \
		exportWindow\exportWidget.h \
		exportWindow\psDialog.h \
		exportWindow\fileDialog.h

moc_comparisonwindow.obj: comparisonWindow\moc_comparisonwindow.cpp comparisonWindow\comparisonwindow.h comparisonWindow\compInputWindow.h \
		exptinfo.h \
		dataStructs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_comparisonwindow.obj comparisonWindow\moc_comparisonwindow.cpp

moc_compInputWindow.obj: comparisonWindow\moc_compInputWindow.cpp comparisonWindow\compInputWindow.h dataStructs.h \
		exptinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_compInputWindow.obj comparisonWindow\moc_compInputWindow.cpp

moc_smallToggle.obj: smallToggle\moc_smallToggle.cpp smallToggle\smallToggle.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_smallToggle.obj smallToggle\moc_smallToggle.cpp

moc_listWindow.obj: listWindow\moc_listWindow.cpp listWindow\listWindow.h probeSetWidget\probeSetWidget.h \
		probe_set\probe_set.h \
		smallToggle\smallToggle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_listWindow.obj listWindow\moc_listWindow.cpp

moc_probeSetWidget.obj: probeSetWidget\moc_probeSetWidget.cpp probeSetWidget\probeSetWidget.h probe_set\probe_set.h \
		smallToggle\smallToggle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_probeSetWidget.obj probeSetWidget\moc_probeSetWidget.cpp

moc_meanPlotWindow.obj: meanPlotWindow\moc_meanPlotWindow.cpp meanPlotWindow\meanPlotWindow.h exptinfo.h \
		probeSetWidget\probeSetWidget.h \
		meanPlotWindow\meanExpressionPlotter.h \
		meanPlotWindow\keyWindow.h \
		probe_set\probe_set.h \
		smallToggle\smallToggle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_meanPlotWindow.obj meanPlotWindow\moc_meanPlotWindow.cpp

moc_meanExpressionPlotter.obj: meanPlotWindow\moc_meanExpressionPlotter.cpp meanPlotWindow\meanExpressionPlotter.h exptinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_meanExpressionPlotter.obj meanPlotWindow\moc_meanExpressionPlotter.cpp

moc_keyWindow.obj: meanPlotWindow\moc_keyWindow.cpp meanPlotWindow\keyWindow.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_keyWindow.obj meanPlotWindow\moc_keyWindow.cpp

moc_experimentWidget.obj: experimentWidget\moc_experimentWidget.cpp experimentWidget\experimentWidget.h exptinfo.h \
		smallToggle\smallToggle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_experimentWidget.obj experimentWidget\moc_experimentWidget.cpp

moc_experimentChooser.obj: experimentChooser\moc_experimentChooser.cpp experimentChooser\experimentChooser.h exptinfo.h \
		experimentWidget\experimentWidget.h \
		experimentChooser\orderChooser\orderWindow.h \
		experimentChooser\sampleMemoryWidget.h \
		smallToggle\smallToggle.h \
		experimentChooser\orderChooser\orderWidget.h \
		dataStructs.h \
		experimentChooser\sampleSelectionWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_experimentChooser.obj experimentChooser\moc_experimentChooser.cpp

moc_sampleMemoryWidget.obj: experimentChooser\moc_sampleMemoryWidget.cpp experimentChooser\sampleMemoryWidget.h experimentChooser\sampleSelectionWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_sampleMemoryWidget.obj experimentChooser\moc_sampleMemoryWidget.cpp

moc_sampleSelectionWidget.obj: experimentChooser\moc_sampleSelectionWidget.cpp experimentChooser\sampleSelectionWidget.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_sampleSelectionWidget.obj experimentChooser\moc_sampleSelectionWidget.cpp

moc_orderWindow.obj: experimentChooser\orderChooser\moc_orderWindow.cpp experimentChooser\orderChooser\orderWindow.h experimentChooser\orderChooser\orderWidget.h \
		exptinfo.h \
		dataStructs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_orderWindow.obj experimentChooser\orderChooser\moc_orderWindow.cpp

moc_orderWidget.obj: experimentChooser\orderChooser\moc_orderWidget.cpp experimentChooser\orderChooser\orderWidget.h exptinfo.h \
		dataStructs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_orderWidget.obj experimentChooser\orderChooser\moc_orderWidget.cpp

moc_logindialog.obj: logindialog\moc_logindialog.cpp logindialog\logindialog.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_logindialog.obj logindialog\moc_logindialog.cpp

moc_passwdchange.obj: passwdchange\moc_passwdchange.cpp passwdchange\passwdchange.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_passwdchange.obj passwdchange\moc_passwdchange.cpp

moc_blastalignpainter.obj: blastAlignPainter\moc_blastalignpainter.cpp blastAlignPainter\blastalignpainter.h probe_set\probe_set.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_blastalignpainter.obj blastAlignPainter\moc_blastalignpainter.cpp

moc_blastAlignWidget.obj: blastAlignPainter\moc_blastAlignWidget.cpp blastAlignPainter\blastAlignWidget.h probe_set\probe_set.h \
		blastAlignPainter\blastalignpainter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_blastAlignWidget.obj blastAlignPainter\moc_blastAlignWidget.cpp

moc_glPlotter.obj: glPlotter\moc_glPlotter.cpp glPlotter\glPlotter.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_glPlotter.obj glPlotter\moc_glPlotter.cpp

moc_statWidget.obj: statPlotter\moc_statWidget.cpp statPlotter\statWidget.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_statWidget.obj statPlotter\moc_statWidget.cpp

moc_statWindow.obj: statPlotter\moc_statWindow.cpp statPlotter\statWindow.h statPlotter\statWidget.h \
		statPlotter\distChooser.h \
		statPlotter\twoDimDistLauncher.h \
		probe_set\probe_set.h \
		stat\twoDimDist.h \
		statPlotter\twoDimDistPlotter.h \
		stat\kernelFunction.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_statWindow.obj statPlotter\moc_statWindow.cpp

moc_distChooser.obj: statPlotter\moc_distChooser.cpp statPlotter\distChooser.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_distChooser.obj statPlotter\moc_distChooser.cpp

moc_twoDimDistLauncher.obj: statPlotter\moc_twoDimDistLauncher.cpp statPlotter\twoDimDistLauncher.h probe_set\probe_set.h \
		stat\twoDimDist.h \
		statPlotter\twoDimDistPlotter.h \
		stat\kernelFunction.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_twoDimDistLauncher.obj statPlotter\moc_twoDimDistLauncher.cpp

moc_twoDimDistPlotter.obj: statPlotter\moc_twoDimDistPlotter.cpp statPlotter\twoDimDistPlotter.h stat\twoDimDist.h \
		stat\kernelFunction.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_twoDimDistPlotter.obj statPlotter\moc_twoDimDistPlotter.cpp

moc_GenAlignWidget.obj: blastAlignPainter\moc_GenAlignWidget.cpp blastAlignPainter\GenAlignWidget.h sequence\sequenceRequest.h \
		probe_set\probe_set.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_GenAlignWidget.obj blastAlignPainter\moc_GenAlignWidget.cpp

moc_annotator.obj: annotator\moc_annotator.cpp annotator\annotator.h annotator\newSession.h \
		annotator\sessionManager\sessionManager.h \
		annotator\sessionManager\sessionWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_annotator.obj annotator\moc_annotator.cpp

moc_newSession.obj: annotator\moc_newSession.cpp annotator\newSession.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_newSession.obj annotator\moc_newSession.cpp

moc_sessionWidget.obj: annotator\sessionManager\moc_sessionWidget.cpp annotator\sessionManager\sessionWidget.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_sessionWidget.obj annotator\sessionManager\moc_sessionWidget.cpp

moc_sessionManager.obj: annotator\sessionManager\moc_sessionManager.cpp annotator\sessionManager\sessionManager.h annotator\sessionManager\sessionWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_sessionManager.obj annotator\sessionManager\moc_sessionManager.cpp

moc_annotationWidget.obj: annotator\annotationWidget\moc_annotationWidget.cpp annotator\annotationWidget\annotationWidget.h probe_set\probe_set.h \
		client.h \
		dataStructs.h \
		chips\chipSelection.h \
		bytevec\bytevec.h \
		exptinfo.h \
		annotator\sessionManager\sessionWidget.h \
		sequence\sequenceRequest.h \
		sequence\seqWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_annotationWidget.obj annotator\annotationWidget\moc_annotationWidget.cpp

moc_annotationViewer.obj: annotator\moc_annotationViewer.cpp annotator\annotationViewer.h annotator\annotationWidget\annotationWidget.h \
		probe_set\probe_set.h \
		client.h \
		dataStructs.h \
		chips\chipSelection.h \
		bytevec\bytevec.h \
		exptinfo.h \
		annotator\sessionManager\sessionWidget.h \
		sequence\sequenceRequest.h \
		sequence\seqWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_annotationViewer.obj annotator\moc_annotationViewer.cpp

moc_genAlignView.obj: blastAlignPainter\moc_genAlignView.cpp blastAlignPainter\genAlignView.h blastAlignPainter\GenAlignWidget.h \
		probe_set\probe_set.h \
		sequence\sequenceRequest.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_genAlignView.obj blastAlignPainter\moc_genAlignView.cpp

moc_seqWidget.obj: sequence\moc_seqWidget.cpp sequence\seqWidget.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_seqWidget.obj sequence\moc_seqWidget.cpp

moc_clusterWindow.obj: clusterWindow\moc_clusterWindow.cpp clusterWindow\clusterWindow.h smallToggle\smallToggle.h \
		client.h \
		meanPlotWindow\meanExpressionPlotter.h \
		clusterWindow\clusterPlotter.h \
		dataStructs.h \
		chips\chipSelection.h \
		probe_set\probe_set.h \
		bytevec\bytevec.h \
		exptinfo.h \
		annotator\sessionManager\sessionWidget.h \
		sequence\sequenceRequest.h \
		sequence\seqWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_clusterWindow.obj clusterWindow\moc_clusterWindow.cpp

moc_clusterPlotter.obj: clusterWindow\moc_clusterPlotter.cpp clusterWindow\clusterPlotter.h client.h \
		meanPlotWindow\meanExpressionPlotter.h \
		dataStructs.h \
		chips\chipSelection.h \
		probe_set\probe_set.h \
		bytevec\bytevec.h \
		exptinfo.h \
		annotator\sessionManager\sessionWidget.h \
		sequence\sequenceRequest.h \
		sequence\seqWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_clusterPlotter.obj clusterWindow\moc_clusterPlotter.cpp

moc_regionWindow.obj: genomicRegion\moc_regionWindow.cpp genomicRegion\regionWindow.h client.h \
		dataStructs.h \
		chips\chipSelection.h \
		probe_set\probe_set.h \
		bytevec\bytevec.h \
		exptinfo.h \
		annotator\sessionManager\sessionWidget.h \
		sequence\sequenceRequest.h \
		sequence\seqWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_regionWindow.obj genomicRegion\moc_regionWindow.cpp

moc_localRegionWidget.obj: genomicRegion\moc_localRegionWidget.cpp genomicRegion\localRegionWidget.h client.h \
		sequence\sequenceRequest.h \
		dataStructs.h \
		chips\chipSelection.h \
		probe_set\probe_set.h \
		bytevec\bytevec.h \
		exptinfo.h \
		annotator\sessionManager\sessionWidget.h \
		sequence\seqWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_localRegionWidget.obj genomicRegion\moc_localRegionWidget.cpp

moc_localRegionView.obj: genomicRegion\moc_localRegionView.cpp genomicRegion\localRegionView.h genomicRegion\localRegionWidget.h \
		client.h \
		sequence\sequenceRequest.h \
		dataStructs.h \
		chips\chipSelection.h \
		probe_set\probe_set.h \
		bytevec\bytevec.h \
		exptinfo.h \
		annotator\sessionManager\sessionWidget.h \
		sequence\seqWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_localRegionView.obj genomicRegion\moc_localRegionView.cpp

moc_jpgView.obj: jpgView\moc_jpgView.cpp jpgView\jpgView.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_jpgView.obj jpgView\moc_jpgView.cpp

moc_imageViewer.obj: jpgView\moc_imageViewer.cpp jpgView\imageViewer.h jpgView\thumbView.h \
		dataStructs.h \
		jpgView\jpgView.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_imageViewer.obj jpgView\moc_imageViewer.cpp

moc_thumbView.obj: jpgView\moc_thumbView.cpp jpgView\thumbView.h jpgView\jpgView.h \
		dataStructs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_thumbView.obj jpgView\moc_thumbView.cpp

moc_inSituView.obj: jpgView\moc_inSituView.cpp jpgView\inSituView.h genomicRegion\localRegionView.h \
		jpgView\imageViewer.h \
		dataStructs.h \
		client.h \
		experiment\experimentBrowser.h \
		jpgView\ishAnnotationEditor.h \
		jpgView\imageAdder.h \
		genomicRegion\localRegionWidget.h \
		sequence\sequenceRequest.h \
		chips\chipSelection.h \
		probe_set\probe_set.h \
		bytevec\bytevec.h \
		exptinfo.h \
		annotator\sessionManager\sessionWidget.h \
		sequence\seqWidget.h \
		jpgView\thumbView.h \
		jpgView\jpgView.h \
		experiment\experimentMaker.h \
		protocol\protocolManager.h \
		protocol\protocolHolder.h \
		protocol\protocolClipboard.h \
		protocol\protocolViewer.h \
		protocol\protocolStepWidget.h \
		jpgView\textWidget.h \
		jpgView\ishTextEntry.h \
		jpgView\ishFloatEntry.h \
		jpgView\fieldCreator.h \
		jpgView\commentAdder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_inSituView.obj jpgView\moc_inSituView.cpp

moc_ishTextEntry.obj: jpgView\moc_ishTextEntry.cpp jpgView\ishTextEntry.h dataStructs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_ishTextEntry.obj jpgView\moc_ishTextEntry.cpp

moc_ishFloatEntry.obj: jpgView\moc_ishFloatEntry.cpp jpgView\ishFloatEntry.h dataStructs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_ishFloatEntry.obj jpgView\moc_ishFloatEntry.cpp

moc_ishAnnotationEditor.obj: jpgView\moc_ishAnnotationEditor.cpp jpgView\ishAnnotationEditor.h dataStructs.h \
		jpgView\textWidget.h \
		jpgView\ishTextEntry.h \
		jpgView\ishFloatEntry.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_ishAnnotationEditor.obj jpgView\moc_ishAnnotationEditor.cpp

moc_ishAnnotationErrorMessage.obj: jpgView\moc_ishAnnotationErrorMessage.cpp jpgView\ishAnnotationErrorMessage.h dataStructs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_ishAnnotationErrorMessage.obj jpgView\moc_ishAnnotationErrorMessage.cpp

moc_textWidget.obj: jpgView\moc_textWidget.cpp jpgView\textWidget.h dataStructs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_textWidget.obj jpgView\moc_textWidget.cpp

moc_pointDrawer.obj: distanceMapper\moc_pointDrawer.cpp distanceMapper\pointDrawer.h distanceMapper\distanceMapper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_pointDrawer.obj distanceMapper\moc_pointDrawer.cpp

moc_distanceViewer.obj: distanceMapper\moc_distanceViewer.cpp distanceMapper\distanceViewer.h distanceMapper\distanceMapper.h \
		distanceMapper\pointDrawer.h \
		distanceMapper\stressPlotter.h \
		distanceMapper\tdPointDrawer.h \
		dataStructs.h \
		customWidgets\fSpinBox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_distanceViewer.obj distanceMapper\moc_distanceViewer.cpp

moc_tdPointDrawer.obj: distanceMapper\moc_tdPointDrawer.cpp distanceMapper\tdPointDrawer.h distanceMapper\distanceMapper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_tdPointDrawer.obj distanceMapper\moc_tdPointDrawer.cpp

moc_traceDrawer.obj: distanceMapper\moc_traceDrawer.cpp distanceMapper\traceDrawer.h dataStructs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_traceDrawer.obj distanceMapper\moc_traceDrawer.cpp

moc_traceViewer.obj: distanceMapper\moc_traceViewer.cpp distanceMapper\traceViewer.h dataStructs.h \
		distanceMapper\traceDrawer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_traceViewer.obj distanceMapper\moc_traceViewer.cpp

moc_stressPlotter.obj: distanceMapper\moc_stressPlotter.cpp distanceMapper\stressPlotter.h distanceMapper\distanceMapper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_stressPlotter.obj distanceMapper\moc_stressPlotter.cpp

moc_fSpinBox.obj: customWidgets\moc_fSpinBox.cpp customWidgets\fSpinBox.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_fSpinBox.obj customWidgets\moc_fSpinBox.cpp

moc_lSpinBox.obj: customWidgets\moc_lSpinBox.cpp customWidgets\lSpinBox.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_lSpinBox.obj customWidgets\moc_lSpinBox.cpp

moc_compareController.obj: distanceMapper\moc_compareController.cpp distanceMapper\compareController.h distanceMapper\distanceViewer.h \
		customWidgets\fSpinBox.h \
		dataStructs.h \
		distanceMapper\traceViewer.h \
		distanceMapper\distanceMapper.h \
		distanceMapper\pointDrawer.h \
		distanceMapper\stressPlotter.h \
		distanceMapper\tdPointDrawer.h \
		distanceMapper\traceDrawer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_compareController.obj distanceMapper\moc_compareController.cpp

moc_protocolStepWidget.obj: protocol\moc_protocolStepWidget.cpp protocol\protocolStepWidget.h dataStructs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_protocolStepWidget.obj protocol\moc_protocolStepWidget.cpp

moc_protocolViewer.obj: protocol\moc_protocolViewer.cpp protocol\protocolViewer.h protocol\protocolStepWidget.h \
		protocol\protocolClipboard.h \
		dataStructs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_protocolViewer.obj protocol\moc_protocolViewer.cpp

moc_protocolHolder.obj: protocol\moc_protocolHolder.cpp protocol\protocolHolder.h dataStructs.h \
		protocol\protocolViewer.h \
		protocol\protocolClipboard.h \
		protocol\protocolStepWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_protocolHolder.obj protocol\moc_protocolHolder.cpp

moc_protocolManager.obj: protocol\moc_protocolManager.cpp protocol\protocolManager.h dataStructs.h \
		protocol\protocolHolder.h \
		protocol\protocolClipboard.h \
		protocol\protocolViewer.h \
		protocol\protocolStepWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_protocolManager.obj protocol\moc_protocolManager.cpp

moc_protocolClipboard.obj: protocol\moc_protocolClipboard.cpp protocol\protocolClipboard.h dataStructs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_protocolClipboard.obj protocol\moc_protocolClipboard.cpp

moc_experimentBrowser.obj: experiment\moc_experimentBrowser.cpp experiment\experimentBrowser.h dataStructs.h \
		experiment\experimentMaker.h \
		protocol\protocolManager.h \
		protocol\protocolHolder.h \
		protocol\protocolClipboard.h \
		protocol\protocolViewer.h \
		protocol\protocolStepWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_experimentBrowser.obj experiment\moc_experimentBrowser.cpp

moc_experimentMaker.obj: experiment\moc_experimentMaker.cpp experiment\experimentMaker.h experiment\experimentMaker.h \
		protocol\protocolManager.h \
		dataStructs.h \
		protocol\protocolHolder.h \
		protocol\protocolClipboard.h \
		protocol\protocolViewer.h \
		protocol\protocolStepWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_experimentMaker.obj experiment\moc_experimentMaker.cpp

moc_imageAdder.obj: jpgView\moc_imageAdder.cpp jpgView\imageAdder.h dataStructs.h \
		jpgView\fieldCreator.h \
		jpgView\commentAdder.h \
		jpgView\jpgView.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_imageAdder.obj jpgView\moc_imageAdder.cpp

moc_fieldCreator.obj: jpgView\moc_fieldCreator.cpp jpgView\fieldCreator.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_fieldCreator.obj jpgView\moc_fieldCreator.cpp

moc_commentAdder.obj: jpgView\moc_commentAdder.cpp jpgView\commentAdder.h dataStructs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_commentAdder.obj jpgView\moc_commentAdder.cpp

moc_indexWidget.obj: indexHistory\moc_indexWidget.cpp indexHistory\indexWidget.h dataStructs.h \
		smallToggle\smallToggle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_indexWidget.obj indexHistory\moc_indexWidget.cpp

moc_historyWidget.obj: indexHistory\moc_historyWidget.cpp indexHistory\historyWidget.h dataStructs.h \
		indexHistory\indexWidget.h \
		smallToggle\smallToggle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_historyWidget.obj indexHistory\moc_historyWidget.cpp

moc_2dplot.obj: 2dplot\moc_2dplot.cpp 2dplot\2dplot.h dataStructs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_2dplot.obj 2dplot\moc_2dplot.cpp

moc_chipSelection.obj: chips\moc_chipSelection.cpp chips\chipSelection.h dataStructs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_chipSelection.obj chips\moc_chipSelection.cpp

moc_chipChooser.obj: chips\moc_chipChooser.cpp chips\chipChooser.h chips\chipSelection.h \
		dataStructs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_chipChooser.obj chips\moc_chipChooser.cpp

moc_exportMeanDialog.obj: dialogs\moc_exportMeanDialog.cpp dialogs\exportMeanDialog.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_exportMeanDialog.obj dialogs\moc_exportMeanDialog.cpp

moc_exportWidget.obj: exportWindow\moc_exportWidget.cpp exportWindow\exportWidget.h expressionplotter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_exportWidget.obj exportWindow\moc_exportWidget.cpp

moc_psDialog.obj: exportWindow\moc_psDialog.cpp exportWindow\psDialog.h exportWindow\exportWidget.h \
		exportWindow\fileDialog.h \
		expressionplotter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_psDialog.obj exportWindow\moc_psDialog.cpp

moc_fileDialog.obj: exportWindow\moc_fileDialog.cpp exportWindow\fileDialog.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_fileDialog.obj exportWindow\moc_fileDialog.cpp

moc_sampleInfoWidget.obj: sampleInfo\moc_sampleInfoWidget.cpp sampleInfo\sampleInfoWidget.h exptinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -omoc_sampleInfoWidget.obj sampleInfo\moc_sampleInfoWidget.cpp

moc_client.cpp: $(MOC) client.h
	$(MOC) client.h -o moc_client.cpp

moc_clientWindow.cpp: $(MOC) clientWindow.h
	$(MOC) clientWindow.h -o moc_clientWindow.cpp

stat\moc_pointPlotter.cpp: $(MOC) stat\pointPlotter.h
	$(MOC) stat\pointPlotter.h -o stat\moc_pointPlotter.cpp

moc_expressionplotter.cpp: $(MOC) expressionplotter.h
	$(MOC) expressionplotter.h -o moc_expressionplotter.cpp

moc_dataView.cpp: $(MOC) dataView.h
	$(MOC) dataView.h -o moc_dataView.cpp

moc_dbQuerier.cpp: $(MOC) dbQuerier.h
	$(MOC) dbQuerier.h -o moc_dbQuerier.cpp

moc_plotWindow.cpp: $(MOC) plotWindow.h
	$(MOC) plotWindow.h -o moc_plotWindow.cpp

comparisonWindow\moc_comparisonwindow.cpp: $(MOC) comparisonWindow\comparisonwindow.h
	$(MOC) comparisonWindow\comparisonwindow.h -o comparisonWindow\moc_comparisonwindow.cpp

comparisonWindow\moc_compInputWindow.cpp: $(MOC) comparisonWindow\compInputWindow.h
	$(MOC) comparisonWindow\compInputWindow.h -o comparisonWindow\moc_compInputWindow.cpp

smallToggle\moc_smallToggle.cpp: $(MOC) smallToggle\smallToggle.h
	$(MOC) smallToggle\smallToggle.h -o smallToggle\moc_smallToggle.cpp

listWindow\moc_listWindow.cpp: $(MOC) listWindow\listWindow.h
	$(MOC) listWindow\listWindow.h -o listWindow\moc_listWindow.cpp

probeSetWidget\moc_probeSetWidget.cpp: $(MOC) probeSetWidget\probeSetWidget.h
	$(MOC) probeSetWidget\probeSetWidget.h -o probeSetWidget\moc_probeSetWidget.cpp

meanPlotWindow\moc_meanPlotWindow.cpp: $(MOC) meanPlotWindow\meanPlotWindow.h
	$(MOC) meanPlotWindow\meanPlotWindow.h -o meanPlotWindow\moc_meanPlotWindow.cpp

meanPlotWindow\moc_meanExpressionPlotter.cpp: $(MOC) meanPlotWindow\meanExpressionPlotter.h
	$(MOC) meanPlotWindow\meanExpressionPlotter.h -o meanPlotWindow\moc_meanExpressionPlotter.cpp

meanPlotWindow\moc_keyWindow.cpp: $(MOC) meanPlotWindow\keyWindow.h
	$(MOC) meanPlotWindow\keyWindow.h -o meanPlotWindow\moc_keyWindow.cpp

experimentWidget\moc_experimentWidget.cpp: $(MOC) experimentWidget\experimentWidget.h
	$(MOC) experimentWidget\experimentWidget.h -o experimentWidget\moc_experimentWidget.cpp

experimentChooser\moc_experimentChooser.cpp: $(MOC) experimentChooser\experimentChooser.h
	$(MOC) experimentChooser\experimentChooser.h -o experimentChooser\moc_experimentChooser.cpp

experimentChooser\moc_sampleMemoryWidget.cpp: $(MOC) experimentChooser\sampleMemoryWidget.h
	$(MOC) experimentChooser\sampleMemoryWidget.h -o experimentChooser\moc_sampleMemoryWidget.cpp

experimentChooser\moc_sampleSelectionWidget.cpp: $(MOC) experimentChooser\sampleSelectionWidget.h
	$(MOC) experimentChooser\sampleSelectionWidget.h -o experimentChooser\moc_sampleSelectionWidget.cpp

experimentChooser\orderChooser\moc_orderWindow.cpp: $(MOC) experimentChooser\orderChooser\orderWindow.h
	$(MOC) experimentChooser\orderChooser\orderWindow.h -o experimentChooser\orderChooser\moc_orderWindow.cpp

experimentChooser\orderChooser\moc_orderWidget.cpp: $(MOC) experimentChooser\orderChooser\orderWidget.h
	$(MOC) experimentChooser\orderChooser\orderWidget.h -o experimentChooser\orderChooser\moc_orderWidget.cpp

logindialog\moc_logindialog.cpp: $(MOC) logindialog\logindialog.h
	$(MOC) logindialog\logindialog.h -o logindialog\moc_logindialog.cpp

passwdchange\moc_passwdchange.cpp: $(MOC) passwdchange\passwdchange.h
	$(MOC) passwdchange\passwdchange.h -o passwdchange\moc_passwdchange.cpp

blastAlignPainter\moc_blastalignpainter.cpp: $(MOC) blastAlignPainter\blastalignpainter.h
	$(MOC) blastAlignPainter\blastalignpainter.h -o blastAlignPainter\moc_blastalignpainter.cpp

blastAlignPainter\moc_blastAlignWidget.cpp: $(MOC) blastAlignPainter\blastAlignWidget.h
	$(MOC) blastAlignPainter\blastAlignWidget.h -o blastAlignPainter\moc_blastAlignWidget.cpp

glPlotter\moc_glPlotter.cpp: $(MOC) glPlotter\glPlotter.h
	$(MOC) glPlotter\glPlotter.h -o glPlotter\moc_glPlotter.cpp

statPlotter\moc_statWidget.cpp: $(MOC) statPlotter\statWidget.h
	$(MOC) statPlotter\statWidget.h -o statPlotter\moc_statWidget.cpp

statPlotter\moc_statWindow.cpp: $(MOC) statPlotter\statWindow.h
	$(MOC) statPlotter\statWindow.h -o statPlotter\moc_statWindow.cpp

statPlotter\moc_distChooser.cpp: $(MOC) statPlotter\distChooser.h
	$(MOC) statPlotter\distChooser.h -o statPlotter\moc_distChooser.cpp

statPlotter\moc_twoDimDistLauncher.cpp: $(MOC) statPlotter\twoDimDistLauncher.h
	$(MOC) statPlotter\twoDimDistLauncher.h -o statPlotter\moc_twoDimDistLauncher.cpp

statPlotter\moc_twoDimDistPlotter.cpp: $(MOC) statPlotter\twoDimDistPlotter.h
	$(MOC) statPlotter\twoDimDistPlotter.h -o statPlotter\moc_twoDimDistPlotter.cpp

blastAlignPainter\moc_GenAlignWidget.cpp: $(MOC) blastAlignPainter\GenAlignWidget.h
	$(MOC) blastAlignPainter\GenAlignWidget.h -o blastAlignPainter\moc_GenAlignWidget.cpp

annotator\moc_annotator.cpp: $(MOC) annotator\annotator.h
	$(MOC) annotator\annotator.h -o annotator\moc_annotator.cpp

annotator\moc_newSession.cpp: $(MOC) annotator\newSession.h
	$(MOC) annotator\newSession.h -o annotator\moc_newSession.cpp

annotator\sessionManager\moc_sessionWidget.cpp: $(MOC) annotator\sessionManager\sessionWidget.h
	$(MOC) annotator\sessionManager\sessionWidget.h -o annotator\sessionManager\moc_sessionWidget.cpp

annotator\sessionManager\moc_sessionManager.cpp: $(MOC) annotator\sessionManager\sessionManager.h
	$(MOC) annotator\sessionManager\sessionManager.h -o annotator\sessionManager\moc_sessionManager.cpp

annotator\annotationWidget\moc_annotationWidget.cpp: $(MOC) annotator\annotationWidget\annotationWidget.h
	$(MOC) annotator\annotationWidget\annotationWidget.h -o annotator\annotationWidget\moc_annotationWidget.cpp

annotator\moc_annotationViewer.cpp: $(MOC) annotator\annotationViewer.h
	$(MOC) annotator\annotationViewer.h -o annotator\moc_annotationViewer.cpp

blastAlignPainter\moc_genAlignView.cpp: $(MOC) blastAlignPainter\genAlignView.h
	$(MOC) blastAlignPainter\genAlignView.h -o blastAlignPainter\moc_genAlignView.cpp

sequence\moc_seqWidget.cpp: $(MOC) sequence\seqWidget.h
	$(MOC) sequence\seqWidget.h -o sequence\moc_seqWidget.cpp

clusterWindow\moc_clusterWindow.cpp: $(MOC) clusterWindow\clusterWindow.h
	$(MOC) clusterWindow\clusterWindow.h -o clusterWindow\moc_clusterWindow.cpp

clusterWindow\moc_clusterPlotter.cpp: $(MOC) clusterWindow\clusterPlotter.h
	$(MOC) clusterWindow\clusterPlotter.h -o clusterWindow\moc_clusterPlotter.cpp

genomicRegion\moc_regionWindow.cpp: $(MOC) genomicRegion\regionWindow.h
	$(MOC) genomicRegion\regionWindow.h -o genomicRegion\moc_regionWindow.cpp

genomicRegion\moc_localRegionWidget.cpp: $(MOC) genomicRegion\localRegionWidget.h
	$(MOC) genomicRegion\localRegionWidget.h -o genomicRegion\moc_localRegionWidget.cpp

genomicRegion\moc_localRegionView.cpp: $(MOC) genomicRegion\localRegionView.h
	$(MOC) genomicRegion\localRegionView.h -o genomicRegion\moc_localRegionView.cpp

jpgView\moc_jpgView.cpp: $(MOC) jpgView\jpgView.h
	$(MOC) jpgView\jpgView.h -o jpgView\moc_jpgView.cpp

jpgView\moc_imageViewer.cpp: $(MOC) jpgView\imageViewer.h
	$(MOC) jpgView\imageViewer.h -o jpgView\moc_imageViewer.cpp

jpgView\moc_thumbView.cpp: $(MOC) jpgView\thumbView.h
	$(MOC) jpgView\thumbView.h -o jpgView\moc_thumbView.cpp

jpgView\moc_inSituView.cpp: $(MOC) jpgView\inSituView.h
	$(MOC) jpgView\inSituView.h -o jpgView\moc_inSituView.cpp

jpgView\moc_ishTextEntry.cpp: $(MOC) jpgView\ishTextEntry.h
	$(MOC) jpgView\ishTextEntry.h -o jpgView\moc_ishTextEntry.cpp

jpgView\moc_ishFloatEntry.cpp: $(MOC) jpgView\ishFloatEntry.h
	$(MOC) jpgView\ishFloatEntry.h -o jpgView\moc_ishFloatEntry.cpp

jpgView\moc_ishAnnotationEditor.cpp: $(MOC) jpgView\ishAnnotationEditor.h
	$(MOC) jpgView\ishAnnotationEditor.h -o jpgView\moc_ishAnnotationEditor.cpp

jpgView\moc_ishAnnotationErrorMessage.cpp: $(MOC) jpgView\ishAnnotationErrorMessage.h
	$(MOC) jpgView\ishAnnotationErrorMessage.h -o jpgView\moc_ishAnnotationErrorMessage.cpp

jpgView\moc_textWidget.cpp: $(MOC) jpgView\textWidget.h
	$(MOC) jpgView\textWidget.h -o jpgView\moc_textWidget.cpp

distanceMapper\moc_pointDrawer.cpp: $(MOC) distanceMapper\pointDrawer.h
	$(MOC) distanceMapper\pointDrawer.h -o distanceMapper\moc_pointDrawer.cpp

distanceMapper\moc_distanceViewer.cpp: $(MOC) distanceMapper\distanceViewer.h
	$(MOC) distanceMapper\distanceViewer.h -o distanceMapper\moc_distanceViewer.cpp

distanceMapper\moc_tdPointDrawer.cpp: $(MOC) distanceMapper\tdPointDrawer.h
	$(MOC) distanceMapper\tdPointDrawer.h -o distanceMapper\moc_tdPointDrawer.cpp

distanceMapper\moc_traceDrawer.cpp: $(MOC) distanceMapper\traceDrawer.h
	$(MOC) distanceMapper\traceDrawer.h -o distanceMapper\moc_traceDrawer.cpp

distanceMapper\moc_traceViewer.cpp: $(MOC) distanceMapper\traceViewer.h
	$(MOC) distanceMapper\traceViewer.h -o distanceMapper\moc_traceViewer.cpp

distanceMapper\moc_stressPlotter.cpp: $(MOC) distanceMapper\stressPlotter.h
	$(MOC) distanceMapper\stressPlotter.h -o distanceMapper\moc_stressPlotter.cpp

customWidgets\moc_fSpinBox.cpp: $(MOC) customWidgets\fSpinBox.h
	$(MOC) customWidgets\fSpinBox.h -o customWidgets\moc_fSpinBox.cpp

customWidgets\moc_lSpinBox.cpp: $(MOC) customWidgets\lSpinBox.h
	$(MOC) customWidgets\lSpinBox.h -o customWidgets\moc_lSpinBox.cpp

distanceMapper\moc_compareController.cpp: $(MOC) distanceMapper\compareController.h
	$(MOC) distanceMapper\compareController.h -o distanceMapper\moc_compareController.cpp

protocol\moc_protocolStepWidget.cpp: $(MOC) protocol\protocolStepWidget.h
	$(MOC) protocol\protocolStepWidget.h -o protocol\moc_protocolStepWidget.cpp

protocol\moc_protocolViewer.cpp: $(MOC) protocol\protocolViewer.h
	$(MOC) protocol\protocolViewer.h -o protocol\moc_protocolViewer.cpp

protocol\moc_protocolHolder.cpp: $(MOC) protocol\protocolHolder.h
	$(MOC) protocol\protocolHolder.h -o protocol\moc_protocolHolder.cpp

protocol\moc_protocolManager.cpp: $(MOC) protocol\protocolManager.h
	$(MOC) protocol\protocolManager.h -o protocol\moc_protocolManager.cpp

protocol\moc_protocolClipboard.cpp: $(MOC) protocol\protocolClipboard.h
	$(MOC) protocol\protocolClipboard.h -o protocol\moc_protocolClipboard.cpp

experiment\moc_experimentBrowser.cpp: $(MOC) experiment\experimentBrowser.h
	$(MOC) experiment\experimentBrowser.h -o experiment\moc_experimentBrowser.cpp

experiment\moc_experimentMaker.cpp: $(MOC) experiment\experimentMaker.h
	$(MOC) experiment\experimentMaker.h -o experiment\moc_experimentMaker.cpp

jpgView\moc_imageAdder.cpp: $(MOC) jpgView\imageAdder.h
	$(MOC) jpgView\imageAdder.h -o jpgView\moc_imageAdder.cpp

jpgView\moc_fieldCreator.cpp: $(MOC) jpgView\fieldCreator.h
	$(MOC) jpgView\fieldCreator.h -o jpgView\moc_fieldCreator.cpp

jpgView\moc_commentAdder.cpp: $(MOC) jpgView\commentAdder.h
	$(MOC) jpgView\commentAdder.h -o jpgView\moc_commentAdder.cpp

indexHistory\moc_indexWidget.cpp: $(MOC) indexHistory\indexWidget.h
	$(MOC) indexHistory\indexWidget.h -o indexHistory\moc_indexWidget.cpp

indexHistory\moc_historyWidget.cpp: $(MOC) indexHistory\historyWidget.h
	$(MOC) indexHistory\historyWidget.h -o indexHistory\moc_historyWidget.cpp

2dplot\moc_2dplot.cpp: $(MOC) 2dplot\2dplot.h
	$(MOC) 2dplot\2dplot.h -o 2dplot\moc_2dplot.cpp

chips\moc_chipSelection.cpp: $(MOC) chips\chipSelection.h
	$(MOC) chips\chipSelection.h -o chips\moc_chipSelection.cpp

chips\moc_chipChooser.cpp: $(MOC) chips\chipChooser.h
	$(MOC) chips\chipChooser.h -o chips\moc_chipChooser.cpp

dialogs\moc_exportMeanDialog.cpp: $(MOC) dialogs\exportMeanDialog.h
	$(MOC) dialogs\exportMeanDialog.h -o dialogs\moc_exportMeanDialog.cpp

exportWindow\moc_exportWidget.cpp: $(MOC) exportWindow\exportWidget.h
	$(MOC) exportWindow\exportWidget.h -o exportWindow\moc_exportWidget.cpp

exportWindow\moc_psDialog.cpp: $(MOC) exportWindow\psDialog.h
	$(MOC) exportWindow\psDialog.h -o exportWindow\moc_psDialog.cpp

exportWindow\moc_fileDialog.cpp: $(MOC) exportWindow\fileDialog.h
	$(MOC) exportWindow\fileDialog.h -o exportWindow\moc_fileDialog.cpp

sampleInfo\moc_sampleInfoWidget.cpp: $(MOC) sampleInfo\sampleInfoWidget.h
	$(MOC) sampleInfo\sampleInfoWidget.h -o sampleInfo\moc_sampleInfoWidget.cpp

####### Install

install: all 

uninstall: 

